google-cloud-storage/src/main/java/com/google/cloud/storage/StorageClass.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java

feat: add support for archive storage class

---

google-cloud-storage/pom.xml
pom.xml

@suztomo
[WARNING] Rule 2: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for org.apache.httpcomponents:httpclient:4.5.10 paths to dependency are:
+-com.google.cloud:google-cloud-storage:1.103.1
+-com.google.http-client:google-http-client:1.34.1
+-org.apache.httpcomponents:httpclient:4.5.10 (managed) <-- org.apache.httpcomponents:httpclient:4.5.11
]

Update HTTP client

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java

feat: add delimiter BlobListOption

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

**Is your feature request related to a problem? Please describe.**
I have a use case that necessitates using the Storage/Bucket write method variants with InputStream arguments. The inputs for my use case to store in Cloud Storage are:
* predominantly already compressed,
* have a wide range of file sizes, from a few KB to GB+,
* we don't always know the size in advance.
**Describe the solution you'd like**
Given that our content is already compressed, I would prefer to avoid spending the CPU time on compressing the content again en route to the Bucket.
**Describe alternatives you've considered**
We have used the `byte[]` variants, with `BlobTargetOption.disableGzipContent` and the Compose request. This is suitable but leaves us with a tuning challenge:
* Buffering these streams into …

add disableGzipContent option for create from InputStream

---

google-cloud-storage/src/test/java/com/google/cloud/storage/BlobWriteChannelTest.java
pom.xml

The default chunk size was increased in https://github.com/googleapis/java-core/pull/87 and was not updated in java-storage unit tests.
This is a quick patch to unblock releasing changes needed to fix: #57 
@elharo, thank you for your patience.

fix: mismatch chunksize

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java

feat: examples of creating a signed url for a blob with generation

---

google-cloud-storage/src/main/java/com/google/cloud/storage/PolicyHelper.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/PolicyHelperTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
pom.xml

Add IAM Conditions Support.
Depends on:
https://github.com/googleapis/java-core/pull/110
Pending Review List:

feat: add IAM Conditions support

---

google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java

fix: use %s instead of %d format specifier in checkArgument

---

README.md

Fixes #<156> (it's a good idea to open an issue first for context and/or discussion)
I think it's advisable to have this info in the readme itself since it's required only for version 1.104 and upwards.

Included google() repository in gradle build

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

feat: add blob.uploadfrom(inputstream)

---

google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java
google-cloud-storage/src/main/java/com/google/cloud/storage/testing/RemoteStorageHelper.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageExceptionTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
pom.xml

fix: rely on google core for SSLException's

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

Reverts googleapis/java-storage#162
Need to revert this for now. The issue is that the [Blob constructor is private](https://github.com/googleapis/java-storage/blob/1f53baa969331a94b5a73319df59711157ef2307/google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java#L545) and it requires creating the object as an [empty object before uploading with an InputStream](https://github.com/googleapis/java-storage/pull/162/files#diff-8c18a40b13cc5c5d90547c273470f5eeR2965-R2966).
The implementation should be derived from the Storage class instead of Blob class to reduce the number of requests.
cc: @dmitry-fa, could you recreate the PR? I haven't prioritized this, apologies for the delay.

Revert "feat: add blob.uploadfrom(inputstream)"

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java

I added the following code:
System.out.printf("Blob updatetime: %s", blob.getUpdateTime());
The output was
Blob updatetime: 1582157090238
I verified that this was ms after epoch:
$ date -d @1582157090
Wed 19 Feb 2020 04:04:50 PM PST
I also traced the code to this function:
https://github.com/googleapis/google-http-java-client/blob/master/google-http-client/src/main/java/com/google/api/client/util/DateTime.java#L53
I assumed that create and delete times used the same format.

docs: clarify documentation on date formats.

---

README.md

fix: storage-client-lib-docs to right location

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobTest.java

fix: Blob.downloadTo() methods do not wrap RetryHelper$RetryHelperException

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobReadChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobReadChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

fix: throw io exception instead of storage exception

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobInfoTest.java

FromHexString() helpers don't handle leading zeros correctly. Added tests and provided a new implementation.

fix: implementations of FromHexString() for md5 and crc32c

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java

fix: Blob API Doc is confusing

---

README.md
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java

cc: @dmitry-fa , @athakor based on pending PRs.
We will continue to update the Storage interface and mark it as InternalExtensionOnly.

fix: surface storage interface expectations correctly.

---

.readme-partials.yaml
.repo-metadata.json
README.md
synth.metadata
synth.py

Custom content is now in `.readme-partials.yaml` so any updates need to go there for now. This will allow automatic updates to the install sections for the latest libraries-bom versions and keep our README format in sync with the other client libraries.
Also fixes a few broken links to the google-cloud-examples that still live in the monorepo.

chore: generate README from templates

---

.readme-partials.yaml

In conjunction with https://github.com/googleapis/synthtool/pull/495, this will allow the README generation to keep the customized versioning section.

chore: override the versioning section in the README

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java

fix: Documentation for Blob.update() and Storage.update() methods is confusing/incorrect

---

google-cloud-storage/src/main/java/com/google/cloud/storage/StorageClass.java

docs: label legacy storage classes in documentation

---

google-cloud-storage/pom.xml
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplMockitoTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
pom.xml

Step toward #179, #270 
Fixes #283

feat: add mockito dependency

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java

docs: catch actual exception in java doc comment

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

fix: blob.reload() does not work as intuitively expected

---

google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplMockitoTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java

part of #270
- mokito tests made stronger: mocks throw an exception if not redefined explicitly
- added missed tests for cases when RPC causes an exception
- Storage reader()/writer() tests converted from easymock to mockito

test: convert a portion of tests from easymock to mockito

---

google-cloud-storage/src/main/java/com/google/cloud/storage/testing/StorageRpcTestBase.java
google-cloud-storage/src/test/java/com/google/cloud/storage/testing/StorageRpcTestBaseTest.java

Allows extending of the StorageRpc interface without breaking cross library dependencies.
Tests outside the Storage library might extend the StorageRpcTestBase class instead of implementing the StorageRpc interface.
Fixes #242

feat: stub implementation of StorageRpc for the sake of testing

---

.github/CODEOWNERS
.repo-metadata.json
synth.metadata

CODEOWNERS is now managed by templates and we can configure the default team in the .repo-metadata.json file.

chore: generate CODEOWNERS from templates

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

feat: delete bucket OLM rules

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

The test is updated to use a new bucket (and delete it at the end) instead of reusing the shared one.
Fixes #349

test: fix flaky testBucketPolicyV1RequesterPays it test

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/pom.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/NotificationInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpcSpans.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
google-cloud-storage/src/main/java/com/google/cloud/storage/testing/StorageRpcTestBase.java
google-cloud-storage/src/test/java/com/google/cloud/storage/NotificationInfoTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/testing/StorageRpcTestBaseTest.java
pom.xml

Fixes #138 
This PR exposing all  the methods of [notifications](https://cloud.google.com/storage/docs/json_api/v1/notifications), also contain the unit test as well as system test of each method.

feat: expose all the methods of notification

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/PostPolicyV4.java

fix: PostPolicyV4.PostFieldsV4.Builder.addCustomMetadataField() allows to add prefixed an not prefixed custom fields

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java

fix(docs): example of Storage#testIamPermissions

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

feat: add support of startOffset and endOffset

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

feat: add support of null to remove the CORS configuration from bucket 

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

The following changes have been done:
- `testListBlobRequesterPays`, `testUpdateBucketRequesterPays` - make independent from other tests
- `testAttemptDeletionObjectTemporaryHold` - restoring operation corrected
- `testBucketAcl`, `testUpdateBucketRequesterPays` , `testBucketPolicyV1RequesterPays` - updated to use the dedicated bucket
- @Before code now is invoked only by a few tests, not all
Fixes: #409

test: ITStorage cleanup

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

feat: expose updateTime field of the bucket

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

feat: add support of customTimeBefore and daysSinceCustomTime

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobInfoTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

feat: add support of customTime metadata

---

google-cloud-storage/pom.xml

fix: use property for kms client version

---

google-cloud-storage/src/main/java/com/google/cloud/storage/testing/RemoteStorageHelper.java

The method `getEventBasedHold` and `getTemporaryHold` return `Boolean` objects which are either `true`, `false` or `null`. In case of a `null` value, this produced a NPE.

fix: prevent NPE in RemoteStorageHelper.cleanBuckets

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobInfoTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

feat: expose timeStorageClassUpdated property of blob's

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

fix: KMS Bad Key error when using existing Blob context to overwrite object

---

synth.py

The .kokoro/nightly/integration.cfg file has manual changes as should be ignoerd by the template generation
See #520

chore: ignore generation of nightly kokoro config

---

pom.xml

chore: add property tag for shared-deps

---

google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java

fix: content-length missing in offset request

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobWriteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

fix: last chunk is retriable

---

google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java

Fix unnecessary options in resumable upload URL by explicitly selecting them instead of iterating though all

fix: unnecessary options in resumable upload URL

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobWriteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

I added three things in this PR:
1. Retries around getting remote offset from GCS
2. Retrying last chunk failures correctly. 
3. Updated documentation for the retry cases
Fixes #709 #687 ☕️

fix: retrying get remote offset and recover from last chunk failures.

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

Port of https://github.com/googleapis/google-cloud-go/pull/3806
Fixes https://github.com/googleapis/java-storage/issues/755

fix(test): update blob paths used in storage.it.ITStorageTest#testDownloadPublicBlobWithoutAuthentication

---

google-cloud-storage/pom.xml

By manually specifying the version of google-api-client here a diamond is created if this version is higher than google-cloud-shared-dependencies.
This PR will actually down grade google-api-client to v1.31.4 until shared-dependencies v1.1.1 is released.

build: update google-api-client to use version from google-cloud-shared-dependencies

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java

Add new checks to ensure a more informative error than NullPointerException is thrown if the StorageObject or it's size are unable to be resolved on the last chunk.
Fixes #839

fix: improve error detection and reporting for BlobWriteChannel retry state

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java

fix: update BucketInfo translation code to properly handle lifecycle rules

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

It looks like the text for this error on the backend has changed
(sometimes) from "Precondition Failed" to "At least one of the
pre-conditions you specified did not hold". I don't think it's
really necessary to check the exact message in any case given
that we do check for a code of 412, which implies a precondition
failure. Switched to check the error reason instead of message.
Fixes #853

test: remove error string matching

---

.github/sync-repo-settings.yaml

The linkage-monitor check on the 1.106.1 patch branch is failing b/c of a mismatched `libraries-bom` dependency reported here: https://github.com/googleapis/java-storage/pull/847/checks?check_run_id=2742109053#step:6:15.
Linkage monitor pulls in the latest libraries-bom & will always fail for this older java-storage version.
This removes linkage-monitor as a required check to pass before merging.

build(ci): remove linkage-monitor to pass 1.106.1 patch ci

---

.github/release-please.yml
.github/sync-repo-settings.yaml

Update branch name in ci config to reduce confusion of tag vs branch
Part of https://github.com/googleapis/java-storage/issues/843

build: rename 1.106.1 patch branch name

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

Adds support for shouldReturnRawInputStream, which will allow users to specify whether the client should auto-decompress gzipped content or not. 
Note: `read(StorageObject, Map<Option, ?>, long, OutputStream)` and `read(StorageObject, Map<Option, ?>, long, int)` in HttpStorageRpc are set up to have different defaults to preserve their original behavior. Before, returnRawInputStream was always set to true, however `read(StorageObject, Map<Option, ?>, long, OutputStream)` had a bug that would cause that to be lost, so it would always turn out to be false (this is why blob.downloadTo and BlobReadChannel.read had different behaviors). That bug is fixed here, but these method signatures now have different defaults to preserve the original behavior. Users can use the new flag to change that …

feat: Add shouldReturnRawInputStream option to Get requests

---

.github/workflows/ci.yaml
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

feat: configure initial sp version

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java

Adds a notice to the docs regarding the broken OLM experience in old versions of the library

docs: add notice about broken OLM experience

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobId.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobIdTest.java

Adds options for creating a blob ID from a storage url and vice versa. Fixes https://github.com/googleapis/java-storage/issues/868

feat: Add from and to storage url options for BlobId

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
google-cloud-storage/src/main/java/com/google/cloud/storage/testing/StorageRpcTestBase.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobWriteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

Add new method StorageRpc#queryResumableUpload which allows getting a shallow StorageObject for a resumable upload session which is complete.
Update BlobWriteChannel to use StoageRpc#queryResumableUpload instead of StorageRpc#get when attempting to validate the upload size of an object when it determines the upload is complete and is on the last chunk.
If a BlobWriteChannel is opened with a conditional like IfGenerationMatch it is not possible to simply get the object, as the object can drift generationally while the resumable upload is being performed.
Related to #839

fix: correct lastChunk retry logic in BlobWriteChannel

---

google-cloud-storage/src/main/java/com/google/cloud/storage/PostPolicyV4.java
google-cloud-storage/src/test/java/com/google/cloud/storage/V4PostPolicyTest.java
pom.xml

V4 Post Policy had an issue where quotes in the json policy would get double escaped (`"` would became `\\"` instead of `\"`), this fixes that issue and updates the conformance tests to the latest version

feat: fix post policy escape bug, update conformance tests

---

google-cloud-storage/src/main/java/com/google/cloud/storage/CopyWriter.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Retrying.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java

* Cleanup and deduplicate error handling/exception translation logic
* Condense all callables to lambdas

chore: cleanup usage of runWithRetries

---

google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/ParallelParameterized.java

The tests are mostly IO bound, it should be safe to increase the number of threads to be higher than the number of cores.
```
[WARNING] Tests run: 739, Failures: 0, Errors: 0, Skipped: 424, Time elapsed: 354.955 s - in com.google.cloud.storage.conformance.retry.ITRetryConformanceTest
```
```
[WARNING] Tests run: 739, Failures: 0, Errors: 0, Skipped: 424, Time elapsed: 96.439 s - in com.google.cloud.storage.conformance.retry.ITRetryConformanceTest
```

chore(test): increase thread count for ParallelParameterized

---

google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/CtxFunctions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/ITRetryConformanceTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/State.java

* test: fix setup for hmacKey create
* test: fix setup for bucket patch
* test: cleanup bucket.lockRetentionPolicy mapping 
* Add precondition predicate to mapping with IfMetagenerationMatch and remove mapping with no guard. Metageneration is a required argument.
* test: fix mappings for ReadChannel
* ReadChannel wrap any exceptions in an IOException, and doesn't extract the cause from the RetryHelperException
* test: fix mappings hmacKey.delete
* As part of setup for delete we need to set the key to inactive
* test: individualMapping(int) -> specificMappings(int...)

test: retry conformance tests fixes, round 2

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/CopyWriter.java
google-cloud-storage/src/main/java/com/google/cloud/storage/LegacyRetryAlgorithmManager.java
google-cloud-storage/src/main/java/com/google/cloud/storage/NewRetryAlgorithmManager.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ResumableMedia.java
google-cloud-storage/src/main/java/com/google/cloud/storage/RetryAlgorithmManager.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Retrying.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageOptions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobWriteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/PackagePrivateMethodWorkarounds.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ResumableMediaTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/SerializationTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageBatchTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RetryTestFixture.java

* RetryAlgorithmManager provides an abstraction point for determining
which ExceptionHandler should be used for a specific call.
* Implement LegacyRetryAlgorithmManager for which all methods return
BaseService.EXCEPTION_HANDLER which is hardcoded everywhere
previously.
* Stub out NewRetryAlgorithmManager which currently extends
LegacyRetryAlgorithmManager, but allows for overriding individual
methods in an incremental manner.
* All usages of BaseService.EXCEPTION_HANDLER in StorageImpl, Blob,
Bucket etc now instead use RetryAlgorithmManager to resolve a
handler per method.
* Refactor Blob to use Retrying#run instead of runWithRetries
* Split starting of a resumable upload session out of BlobWriteChannel
to ResumableMedia. This decouple the ability to instantiate a
BlobWriteChannel …

chore(retry): introduce RetryAlgorithmManager

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
google-cloud-storage/src/main/java/com/google/cloud/storage/testing/StorageRpcTestBase.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobWriteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

1. #816
2. #852
3. #846 & #918

fix(1.113.14-sp): backport critical bug fixes

---

google-cloud-storage/src/main/java/com/google/cloud/storage/NewRetryAlgorithmManager.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/CtxFunctions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/State.java
google-cloud-storage/src/test/resources/com/google/cloud/storage/conformance/retry/testNamesWhichShouldSucceed.txt

* fix incorrect evaluation of idempotency for objects.compose (now generation, previously metageneration)
* add mapping for non-idempotent objects.compose invocation
* add CtxFunction to construct a ComposeRequest relative to the state
* add ComposeRequest handling to state

test(retry): fix objects.compose tests

---

google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RetryTestFixture.java

when debugging a failing test, the retry_test state will now be queried allowing for its presence to show in request logs to aid debugging.

test(retry): decouple querying retry_test state from test success

---

google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/ITRetryConformanceTest.java

* If an overly specific allowed filter can prevent any test cases from being passed to the runner, add validation to ensure there is at least one test case.

test(retry): add validation to ensure at least one test case is resolved

---

google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultStorageRetryStrategy.java
google-cloud-storage/src/test/java/com/google/cloud/storage/DefaultRetryHandlingBehaviorTest.java

In addition to providing the new handlers which are validated to some extent with the retry conformance suite, we also want to ensure we maintain support for "java specific" errors which historically are already handled my the core library. In some ways this also functions as a regression suite of errors we want to keep track of for retry purposes.

test(retry): add a test which ensures expected behavior of new retry handlers

---

google-cloud-storage/src/main/java/com/google/cloud/storage/StorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageRetryStrategy.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobWriteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/PackagePrivateMethodWorkarounds.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplMockitoTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RetryTestFixture.java

1. Add new configuration option `StorageOptions.Builder#setStorageRetryStrategy`
2. Add new interface `StorageRetryStrategy`
3. Update all calls to be made idempotency aware
4. Change default behavior of automatic retries to only retry those operations which are deemed to be idempotent
5. Add @deprecated method `StorageRetryStrategy.getLegacyStorageRetryStrategy` providing access to a strategy which matches the previous sometimes unsafe behavior

feat: update all automatic retry behavior to be idempotency aware

---

google-cloud-storage/src/main/java/com/google/cloud/storage/StorageOptions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageOptionsTest.java

When calling `StorageOptions#toBuilder()` after creating the builder the host was explicitly set to the default host. This change removes that behavior instead moving the setting of the default host to the instantiation of a new builder.
Add unit tests to ensure host is set to the expected values based on different ways of creating an instance of StorageOptions.
Related:
* https://github.com/googleapis/google-cloud-java/pull/6579
* https://github.com/googleapis/google-cloud-java/issues/7004
* https://github.com/googleapis/google-cloud-java/pull/7034

fix: update StorageOptions to not overwrite any previously set host

---

google-cloud-storage/pom.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultStorageRetryStrategy.java
google-cloud-storage/src/test/java/com/google/cloud/storage/DataGeneration.java
google-cloud-storage/src/test/java/com/google/cloud/storage/DefaultRetryHandlingBehaviorTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/PackagePrivateMethodWorkarounds.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/CleanupStrategy.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RetryTestFixture.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/TestBench.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobWriteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

Update DefaultStorageRetryStrategy to account for EOF errors from Json. When parsing json it's possible we've only received a partial document and parsing will fail. If an unexpected EOF happens from parsing and the request is idempotent retry it.
Add two new integration tests which leverage the testbench to force the EOF to happen upon the completion of the resumable session.
* Add 0B offset test
* Add 10B offset test
Add new cases to DefaultRetryHandlingBehaviorTest to ensure continued expected handling for the new EOF behavior.
* Make TestBench.java (and its associated Builder) public to allow for use outside the retry conformance test package
* Create new JUnit @rule DataGeneration moving com.google.cloud.storage.it.ITStorageTest#randString to it and change the signature to produce a …

fix: update retry handling to retry idempotent requests that encounter unexpected EOF while parsing json responses

---

README.md
samples/snippets/src/main/java/com/example/storage/ConfigureRetries.java
samples/snippets/src/test/java/com/example/storage/ConfigureRetriesTest.java

docs: add new sample storage_configure_retries

---

samples/snippets/src/main/java/com/example/storage/ConfigureRetries.java

Comment fixes from review after merge of #1152

docs: update comments

---

google-cloud-storage/src/test/java/com/google/cloud/storage/DataGeneration.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/TestBench.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobWriteChannelTest.java

* Update ITBlobWriteChannelTest to be compliant with new enforcements
* Unique bucket per test
* Explicitly do not attempt to get the object with generation 0

test: bump storage-testbench to v0.11.0

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

Disabling testHmacKey because it's preventing us from merging PR's. There's an GCP Project OrgPolicy issue that needs to be resolved and not a backend issue. 
https://github.com/googleapis/java-storage/issues/1240 ☕️

test: skip testHmacKey test

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobReadChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobReadChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadChannelTest.java

The ReadChannel returned from storage.reader and blob.reader now also implemented LimitableReadChannel which allows limiting the max number of bytes the channel will make available for read.
This can be used in conjunction with seek to allow for range gets of objects independent of any buffer or chunk sizes.
See the integration tests for an example of how this could be used.

feat: allow limiting ReadChannel

---

samples/snapshot/pom.xml

The samples build on https://github.com/googleapis/java-storage/pull/1293 is broken due to 
`Failed to execute goal on project storage-snapshot: Could not resolve dependencies for project com.google.cloud:storage-snapshot:jar:1.2.0: Could not find artifact com.google.cloud:google-cloud-storage:jar:2.4.6-SNAPSHOT `
It appears the version is not updating properly. This should fix the issue.

deps: allow snapshot to update properly

---

README.md
samples/snippets/src/test/java/com/example/storage/ITHmacSnippets.java

Adjust retry settings for HMAC samples to make sure that these requests are getting retried. 
This was also needed in Go (See https://github.com/GoogleCloudPlatform/golang-samples/blob/main/storage/service_account/hmac/hmac_test.go#L195)
Should fix https://github.com/googleapis/java-storage/issues/1302

docs: adjust retry settings for hmac samples

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

test: Updates for Dual Region and testing

---

.github/sync-repo-settings.yaml
.kokoro/presubmit/graalvm-native.cfg
owlbot.py

This PR reduces the discrepancy between the standard Java and Native Image kokoro job. It should also fix the following error:
```
java.lang.AssertionError: Unable to determine service account email
at com.google.cloud.storage.it.ITStorageTest.testHmacKey(ITStorageTest.java:2472)
```

fix(java): add service account email to Native Image testing kokoro job

---

samples/native-image-sample/pom.xml

For GraalVM native image, GAX provides required metadata. We no longer need native-image-support-java module.

docs(sample): removing unnecessary native-image-support dependency

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Crc32cValue.java
google-cloud-storage/src/test/java/com/google/cloud/storage/Crc32cValueTest.java

Provides compiler validation of trying to concatenate two crc32c values

chore: add Crc32cValue type

---

google-cloud-storage/pom.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BackwardCompatibilityUtils.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Conversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Utils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/DateTimeCodecPropertyTest.java

* Add Codec<DateTime, OffsetDateTime> for apiary conversion
* Add Utils#RFC_3339_DATE_TIME_FORMATTER
* Add BackwardCompatibilityUtils#millisOffsetDateTimeCodec to provide compatibility with existing Long centric apis
* Update BucketInfo and BucketInfo.Builder to prefer java.time types instead of Long
* Update ApiaryConversions for BucketInfo to use new java.time types
Update the following files to now be OffestDateTime instead of Long
* BlobInfo#customTime
* BlobInfo#deleteTime
* BlobInfo#updateTime
* BlobInfo#createTime
* BlobInfo#timeStorageClassUpdated
* BlobInfo#retentionExpirationTime
* BucketInfo#retentionEffectiveTime
* IamConfiguration#uniformBucketLevelAccessLockedTime

feat: migrate model classes to use java.time instead of Long

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ServiceAccountPropertyTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/ServiceAccountArbitraryProvider.java
google-cloud-storage/src/test/resources/META-INF/services/net.jqwik.api.providers.ArbitraryProvider

* Add conversion for com.google.storage.v2.ServiceAccount
* Add property test to ensure round trip decode -> endode -> decode succeeds
* Add ServiceAccountArbitraryProvider

feat: add skeleton implementation of GrpcStorageImpl#getServiceAccount

---

google-cloud-storage/src/test/java/com/google/cloud/storage/BaseConvertablePropertyTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ServiceAccountPropertyTest.java

All Convertable types share a common set of properties that they need to provide. This new class will ensure in a central location they do.
First property: a round trip through the codec should provide a value equal to the initial input

test: introduce BaseConvertablePropertyTest

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

Previously testHmacKey would clobber any existing hmac keys for the service account when it started running, and multiple points during the test. This change updates the behavior to only try and cleanup an hmac key if it's been more than 24hrs since last updated.
Additionally, a project is only allowed 5 hmac keys total, creating 4 keys in the test to check pagination creates contention for other simultaneous runs that need to use hmac keys. I've removed this, the logic for pagination is the same as for other things like blobs and buckets we can depend on those to ensure dynamic page sizing works.

test: update ITStorageTest#testHmacKey to be courteous

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BackwardCompatibilityUtils.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/HmacKey.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Utils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/DateTimeCodecPropertyTest.java

Fields which map to apiary DateTime RFC 3339 fields will now also have
a preferred java.time.OffsetDateTime getter & setter.
Fields which map to apiary long to represent a duration in epoch millis
will no also have a preferred java.time.Duration getter & setter.
All new methods currently have the name of the corresponding java.time
type appended to the property name.
* BlobInfo#createTime
* BlobInfo#customTime
* BlobInfo#deleteTime
* BlobInfo#retentionExpirationTime
* BlobInfo#timeStorageClassUpdated
* BlobInfo#updateTime
* Blob#createTime
* Blob#customTime
* Blob#deleteTime
* Blob#retentionExpirationTime
* Blob#timeStorageClassUpdated
* Blob#updateTime
* BucketInfo.CreatedBeforeDeleteRule
* BucketInfo.DeleteRule
* BucketInfo.IsLiveDeleteRule
* BucketInfo.NumNewerVersionsDeleteRule
* …

feat: refactor model classes to prefer to java.time types

---

google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/DefaultRetryHandlingBehaviorTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/ITRetryConformanceTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/TestRetryConformance.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITDownloadToTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

When invoking downloadTo(..., OutputStream) if a retry was attempted the proper byte
offset was not being sent in the retried request. Update logic of HttpStorageRpc.read
to manually set the range header rather than trying to rely on MediaDownloader to do
it along with not automatically decompressing the byte stream.
Update ITRetryConformanceTest to run Scenario 8 test cases, which cover resuming a
download which could have caught this error sooner.
Update StorageException.translate(IOException) to classify `IOException: Premature EOF`
as the existing retryable reason `connectionClosedPrematurely`. Add case to
DefaultRetryHandlingBehaviorTest to ensure conformance to this categorization.
Break downloadTo integration test out into their own class, and separate
the multiple scenarios being …

fix: update request method of HttpStorageRpc to properly configure offset on requests

---

google-cloud-storage/src/test/java/com/google/cloud/storage/Crc32cUtilityPropertyTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/StorageArbitraries.java

Add property based testing to Crc32cCombineGoogle utility

test: add property testing to Crc32cCombineGoogle

---

google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultBufferedReadableByteChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/DefaultBufferedReadableByteChannelTest.java

New property test against arbitrarily generated data along with buffer size, and app read size.
Ensure the expected number of reads and their sizes are returned for a specific data size.
Ensure channel is closed after full read, and throws a ClosedChannelException when attempted to read after close

test: add property test for DefaultBufferedReadableByteChannel

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/BucketArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/ObjectArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/StorageArbitraries.java

1. Added Bucket+ProjectID model in BucketInfo and update setters and getters for Bucket name to use this new model.
1. Added setters and getters for projectID in BucketInfo and Bucket (using BucketName helper)
1. Added unformatted bucket name into property based test "bucket" vs. "projects/project-id/buckets/bucket-id"
1. Support default value when presented with unformatted bucket name to  use "_" for project id
1. Added fall for unformatted into log bucket parser in grpc conversions.
1. Tested unformatted bucket name only for log bucket name (do not do it for BucketInfo)

feat: support formatted bucket name with projectID

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/TransportCompatibility.java
google-cloud-storage/src/test/java/com/google/cloud/storage/TransportCompatibilityTest.java

All Storage methods have been updated to specify which transport they are compatible with
All "Syntax" Model classes have had their rpc methods annotated to specify which transport they are compatible with
Unsupported Signed Url methods in GrpcStorageImpl have been updated to throw an UnsupportedOperationException.
Additionally, annotate all gRPC related public methods with `@BetaApi`

chore: add TransportCompatibility annotations

---

google-cloud-storage/src/test/java/com/google/cloud/storage/BaseConvertablePropertyTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/CIUtils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/GracefulConformanceEnforcement.java

GitHub Actions UI can lag quite a bit when there is a fair amount of console output, in an effort to reduce this update BaseConvertablePropertyTest to only report edgeCases when not running on GitHub Actions or if running in integration test mode.
Add CIUtils class to corral CI Environment related util methods.

chore(test): reduce console output when running on GitHub

---

google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultBufferedWritableByteChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/DefaultBufferedWritableByteChannelTest.java

New property test against arbitrarily generated data along with buffer size, and app write size.
Ensure the expected number of writes and their sizes are performed for a specific data size.
Ensure the expected number of flushes are performed, and at the correct intervals.
Ensure channel is closed after full read, and throws a ClosedChannelException when attempted to read after close

test: add property test for DefaultBufferedWritableByteChannel

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BufferHandle.java
google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultBufferedReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultBufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicDownloadSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicResumableUploadSessionBuilder.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BufferHandleTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/DefaultBufferedReadableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/DefaultBufferedWritableByteChannelTest.java

Eagar allocation of large buffers can cause significant memory pressure for users
who are processing many objects in parallel or processing small objects. Since our
Buffered Channels are present to smooth out rpc sizes which can have high latencies
we do not want to unnecessarily allocate a buffer.
Buffered Read & Write Channel already minimize unnecessary copies into our buffer,
coupled with this change, if a user is reading/writing buffers the same size as the
configured buffer size we will never actually allocate a buffer thereby saving on
unnecessary memory consumption.

chore: refactor Buffered Channels such that buffer allocation is now lazy

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicDownloadSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcBlobReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Hasher.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageV2ProtoUtils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageV2ProtoUtilsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/BucketArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/ObjectArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/StorageArbitraries.java

Update readAllBytes and downloadTo methods to use unbuffered read channel, instead of reader
Update *ReadableByteChannelSessions to take a ReadObjectRequest instead of Object
Update Hasher#validate to be lazy with regard to the ByteBuffer, this ensures no new byte buffer is created if it isn't needed in the case of noop.
Add StorageArbitraries.Objects#name()
Move StorageArbitraries.bucketName() -> StorageArbitraries.Buckets#name()
Add StorageArbitraries.alnum() and cleanup usages in Buckets.name()

chore: refactor GrpcStorageImpl#read* methods to use more specific channels

---

samples/native-image-sample/pom.xml

As described in the official doc, the [junit-native-plugin can be safely removed](https://graalvm.github.io/native-build-tools/latest/index.html#_release_0_9_6) if we are using versions 0.9.6 and later of the ` native-maven-plugin `
maven-surefire-plugin 2.22.2 seemed to have required `junit-platform-native` and removing this dependency resulted in 
```
R] Test configuration file wasn't found. Make sure that test execution wasn't skipped.
```
However, upgrading the surefire plugins and removing `junit-platform-native` results in a successful build. 
To run tests in native image mode, call the following command: `mvn test -Pnative`

docs(sample): upgrade maven-surefire and remove junit-platform-native

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ZOpt.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ZOptTest.java

StorageRpc.Option is a difficult and often error prone to use, ZOpt tries to make it easier and safer to work with.
ZOpt defines a set of constants matching those from StorageRpc.Option, except that ZOpt carries the generic type information with it rather than dropping it. This makes usage of these options easier and type safe.

chore: introduce ZOpt

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/TestBench.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITGrpcTest.java

Support grpc api testing with testbench
blocked until https://github.com/googleapis/storage-testbench/pull/376 is released.

test: update testbench to support grpc endpoint

---

samples/snippets/src/main/java/com/example/storage/bucket/CreateBucketDualRegion.java
samples/snippets/src/test/java/com/example/storage/bucket/CreateBucketDualRegionTest.java

docs: Refactor Custom Dual Region sample to work with API changes

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketFixture.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITDownloadToTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITGrpcTest.java

Create a JUnit Rule which can manage the lifecycle of a temporary bucket. A bucket will be created by the rule, and then emptied and deleted upon test completion.
Update some of the IT*Test classes to use the new fixture when applicable.
Update bucket name handling in some GrpcStorageImpl methods.
Add simplistic listBlobs and listBuckets tests to ITGrpcTest

test: add BucketFixture

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/CSEKSupport.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITOptionRegressionTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/RequestAuditing.java

*  add tests for metageneration{Not,}Match(long)
*  add tests for {en,de}cryptionKey({Key,String})
*  add tests for userProject
* Bucket.BucketSourceOption#userProject is somehow busted, and doesn't work for exists/refresh/delete due to some enum exception
*  add tests for predefined{DefaultObject,}Acl
*  add tests for disableGzipContent()
*  add tests for generation{Not,}Match and doesNotExist
*  add tests for detectContentType
*  add tests for kmsKeyName
*  add tests for projection
*  add tests for requestedPolicyVersion
*  add tests for projectId
*  add tests for list operations
*  add tests for fields(*) options
*  add tests for BlobWriteOption#{md5,crc32c}Match
*  add tests for {meta,}generation{Not,}Match extractors

test: add regression tests for each Option on our public api

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java

For some upcoming testing we will need to swap the instance of StorageOptions on BlobWriteChannel to verify cross configuration compatibliity.

chore: add internal blobWriteChannel hook to override StorageOptions

---

google-cloud-storage/src/main/java/com/google/cloud/storage/package-info.java

Internal bug 216304555, documents the thread safety of this library

docs: Document thread safety of library

---

google-cloud-storage/pom.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/Crc32cValue.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicDownloadSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Hasher.java
google-cloud-storage/src/test/java/com/google/cloud/storage/FakeServer.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ResultRetryAlgorithmCompatibilityTest.java

Add new FakeServer which allows defining an in process grpc storage service rather than trying to fight with mocks.
Add test for GapicUnbufferedReadableByteChannel to verify:
* retries happening at the ServerStream level return sound data
* Generation changing between a resumed read results in an IOException rather than proceeding
* checksum mismatch for an individual ChecksummedData
* checksum mismatch across all cumulative ChecksummedData
* Move Crc32cValue#nullSafeConcat into Hasher so that it can be context aware
whether to actually perform any computation
Wire in Automatic Retries for ReadObject operations
The ServerStream provided by gax isn't friendly to decoration for its iterator.
Instead, leverage the built-in stream resumption provided by gax.
In order to provide compatibility …

test: add error handling and retry tests for GapicUnbufferedReadableByteChannel

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/test/java/com/google/cloud/storage/UnifiedOptsGrpcTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITGrpcTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/HmacKeyMetadataArbitraryProvider.java

* GrpcStorageImpl#createHmacKey
* GrpcStorageImpl#getHmacKey
* GrpcStorageImpl#updateHmacKey
* GrpcStorageImpl#deleteHmacKey
Add tests for each Hmac method to ITGrpcTest
Depends on #1568

feat: implement GrpcStorageImpl#*HmacKey

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Retrying.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GrpcTransformPageDecoratorTest.java

Update TransformPageDecorator to apply automatic retires to individual page fetches.
To accomplish page granularity for retries I've replaced TransformingIterator with
a page producing Stream, where each page can then be expected into a single Iterator.
Add new interface Retrying.RetryingDependencies to provide a marker for the need
of RetrySettings and an ApiClock so we're not coupled to full StorageOptions
instances.
Renamed Retrying.run(HttpStorageOptions, ...) to Retrying.runHttp(HttpStorageOptions, ...)
to remove ambiguity. Ideally we'll be able to remove this in the future once grpc
and http are both able to use the same approach for configuring gccl-invocation-id.
Refactor much of GrpcTransformPageDecoratorTest.java to provide a data driven
implementation of UnaryCallable removing …

chore: implement retries for List operations in GrpcStorageImpl

---

google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultBufferedReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicDownloadSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcBlobReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GzipReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageByteChannels.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/test/java/com/google/cloud/storage/AutoClosableFixture.java
google-cloud-storage/src/test/java/com/google/cloud/storage/FakeServer.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GzipReadableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/TestUtils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITDownloadToTest.java

Create new GzipReadableByteChannel which will be wired into the download session channel
if enabled.
By default, auto decompression IS NOT enabled, GrpcStorageImpl is responsible for translating
the meaning from `RETURN_RAW_INPUT` stream to `autoGzipDecompress`. Enabling means additional
startup effort and memory overhead due to loss of buffer control.
JUnit 4 Rule which can be used to bind some `AutoClosable` to a `@ClassRule` or `@Rule` lifecycle

chore: wire automatic gzip decompression into DownloadSessionBuilder and channels

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java

I forgot to update as part of #1576

chore: update TransportCompatibility annotations for hmac operations

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ByteSizeConstants.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ChunkSegmenter.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicWritableByteChannelSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcBlobWriteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Hasher.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ResumableWrite.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java
google-cloud-storage/src/main/java/com/google/cloud/storage/WriteFlushStrategy.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ChunkSegmenterTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GapicUnbufferedWritableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/TestUtils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/TransportCompatibilityTest.java

two new tests that validate correct request packing and response handling when
performing a direct or resumable upload.
Create a constants class to keep track of the common byte size values used
throughout the library.
Reduce the surface area on the constructor, moving Write callable, Hasher,
ByteStringStrategy, etc. out since GapicUnbufferedWritableByteChannel itself
doesn't use them.
Change ChunkSegmenter to no longer be static, instead taking a handle the
Hasher, ByteStringStrategy and maxSegmentSize which are necessary for later
computations of segmentBuffers.
Change FlusherFactory to no longer take the write callable, instead any
dependency is expected to be bound into the state of the factory. Flushers will
now maintain a handle to the write callable when they are constructed. …

test: add first two low level tests for grpc upload

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ResumableWrite.java
google-cloud-storage/src/main/java/com/google/cloud/storage/WriteCtx.java
google-cloud-storage/src/main/java/com/google/cloud/storage/WriteFlushStrategy.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GapicUnbufferedWritableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/WriteFlushStrategyTest.java

Update WriteFlushStrategy to inject bucket id into x-goog-request-params upon opening the stream.
Fixes [b/238792234](http://b/238792234)

chore: update WriteFlushStrategy to inject bucket id

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketFixture.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITGrpcTest.java

Update BucketFixture to provide its own implementation of bulk object delete.
The method in RemoteStorageHelper relies upon batch methods which aren't
supported for grpc.

test: add grpc integration tests for simplistic object read/write

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BackwardCompatibilityUtils.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BackwardCompatibilityUtilsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ResultRetryAlgorithmCompatibilityTest.java

For grpc retries, we need to do things in terms of StorageException in order to
be compatible with the existing StorageRetryStrategy behaviors which are built
around inspecting json type errors.

chore: update retry compatibility to work via StorageException

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/HttpStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITStorageLifecycleTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/SerializationTest.java

* Update SerializationTest lifecycle to account for the fact that instances of
Storage now have `.close()`
* Add each new UnifiedOpt to the list of serializable things
* Add explicit HttpStorageOptions and GrpcStorageOptions to list of serializable
things
* Update GrpcStorageOptions to integrate with ServiceOptions caching of service
instances
* Add new test to ensure proper integration with ServiceOptions caching of service
instances

test: add new classes to SerializationTest

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/BucketArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/HmacKeyMetadataArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/ObjectArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/StorageArbitraries.java

* Wire etags through for the following messages/models
* Bucket <-> BucketInfo
* ObjectAccessControl <-> Acl
* Object <-> BlobInfo
* HmacKeyMetadata <-> HmacKeyMetadata
* Wire acls through for the following messages/models
* Bucket <-> BucketInfo
* BucketAccessControl <-> Acl
* ObjectAccessControl <-> Acl
* Object <-> BlobInfo
Additionally, clean up some other todos from GrpcConversions
1. blobInfoEncode owner
2. blobInfoDecode owner
3. Enum valueOf empty string. Guard each Enum.valueOf to prevent empty string being passed.
Update property based tests to provide etags, empty enum string values, ACLs
Adding edgcases of empty string to storageClass cascaded to message internal usages of its
arbitrary, requiring clean up of StorageArbitraries.Buckets#action() and …

chore: wire etags and acls through GrpcConversions

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketLifecycleTest.java

This PR adds the GRPC Client to ITBucketLifecycleTest as well as fixes some bugs that were uncovered by getting this test running.
1. The way we were generating the field mask was not correct for GRPC. GRPC does not allow you to specify immutable fields in the fieldmask. We must filter these values out.
2. Adding AbortMPULifecycle Action to the Lifecycle rules codec.

fix: Fix bugs discovered by ITBucketLifecycleTest

---

google-cloud-storage/pom.xml
google-cloud-storage/src/test/java/com/google/cloud/storage/GapicReadTimeoutTest.java

In #1615 we started using GsonFactory in some of our tests, as a result dependency enforcement required us to acknowledge the new dependency. Since we were using it in tests, I set the scope to `test`. Setting the scope to `test` actually breaks the transitive dependency resolution performed by the flatten plugin. This results in google-http-client-gson being exclude entirely from the resulting pom and causing downstream consumers to receive a NoClassDefFoundError.
Now, instead of setting the scope to `test` we're explicitly stating that the dependency enforcement plugin should ignore google-http-client-gson.
Related to #1615

build(fix): update maven config for dependency enforcement of google-http-client-gson

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicCopyWriter.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcBlobReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcBlobWriteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Utils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/PackagePrivateMethodWorkarounds.java

Only remaining use is for notification codec, which will be cleaned up at a later point
For `RestorabeState<*> capture()` methods raise an error that they are currently
only supported for HTTP. gRPC channel configuration isn't something that is
Serializable. We'll need to figure out how we'll want to provide a Serializable
thing that can try and capture the boostrapping that takes place.

chore: cleanup outstanding use of todo() method

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicWritableByteChannelSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcBlobWriteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Retrying.java
google-cloud-storage/src/main/java/com/google/cloud/storage/WriteFlushStrategy.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GapicUnbufferedWritableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GrpcTransformPageDecoratorTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/TestUtils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/WriteFlushStrategyTest.java

Plumb through the necessary items to allow retrying to take place in WriteStrategy.FlushOnEveryFlusher#flush.
Update corresponding builders along with this to pass through the necessary items.
* Move {Unbuffered,Buffered}{Direct,Resumable}UploadBuilder classes to be nested in their logical "parent builders" to allow closing over fields set at the higher level
* Move GrpcTransformPageDecoratorTest.java#retryingDeps -> TestUtils#defaultRetryingDeps

feat: implement automatic retry for resumable uploads

---

.github/release-please.yml
.github/sync-repo-settings.yaml

chore: setting up 2.6.x branch

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Buffers.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicWritableByteChannelSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcBlobWriteChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java

Update GrpcBlobWriteChannel to always create and finalize an upload session even if `write` is never called. This change follows the behavior of BlobWriteChannel today and is done for compatibility sake.
Fixes b/248605626

fix: update GrpcBlobWriteChannel to share compatible behavior with BlobWriteChannel

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ByteSizeConstants.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUploadSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcBlobWriteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Retrying.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GapicUnbufferedWritableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GrpcStorageImplUploadRetryTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GrpcTransformPageDecoratorTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/TestUtils.java

* com.google.cloud.storage.GrpcStorageImpl.create(com.google.cloud.storage.BlobInfo, byte[], int, int, com.google.cloud.storage.Storage.BlobTargetOption...)
* com.google.cloud.storage.GrpcStorageImpl.createFrom(com.google.cloud.storage.BlobInfo, java.nio.file.Path, int, com.google.cloud.storage.Storage.BlobWriteOption...)
Set default chunkSize to 16MiB instead of 15MiB. While 15MiB is evenly divisible by 256KiB, 16MiB is also evenly divisible by 2MiB the max number of bytes that can be provided in a WriteObjectRequest.

chore: wire automatic retries into direct uploads for GrpcStorageImpl

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Conversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/TransportCompatibility.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/test/java/com/google/cloud/storage/SerializationTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplMockitoTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITOptionRegressionTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITReadMaskTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/RequestAuditing.java

Both JSON and gRPC provide the means of being able to specify a mask to select specific fields be returned in a response. However, there are slightly differing approaches taken between the different transports as well as outward facing impacts for existing code of our client.
Primary difference between JSON and gRPC is null vs default values. Several fields in gRPC can be excluded from the response from GCS but protobuf will still yield a value for our decoder. To address this compatibility issue, in the case of gRPC if a read_mask is defined we will clear out any non-selected field after decoding.
The new NamedField construct forces a decoupling from FieldSelector and it's associated Helper as JSON and gRPC have different formats for specifying their selectors/masks.
We are no longer …

feat: wire through read_mask for GrpcStorageImpl methods related to Blob and Bucket

---

google-cloud-storage/pom.xml
google-cloud-storage/src/test/java/com/google/cloud/storage/ShimClientTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITNotificationTest.java
google-cloud-storage/src/test/resources/META-INF/native-image/com/google/cloud/storage/native-image.properties

test(deps): bump junit-platform.version to 5.9.1
Also removed a dangling bucket deletion in ITNotificationTest which was resulting in an exception at cleanup time.

chore: fix native-image.properties to allow running jqwik tests

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BackwardCompatibilityUtils.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Utils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketTest.java

A Retention Periods duration is expressed in seconds, not milliseconds. Update test to ensure the retention period duration that is processed is interpreted in the correct units.

fix: update codec handling for Bucket Retention Period

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcBlobReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageV2ProtoUtils.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GzipReadableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageV2ProtoUtilsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/ITRetryConformanceTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadChannelTest.java

* fix: update GrpcBlobReadChannel to set limit as a number of bytes rather than end_offset
* fix: update StorageV2ProtoUtils#validation to treat limit as number of bytes to read rather than end_offset
* test: mark com.google.cloud.storage.it.ITBlobReadChannelTest.testReadChannelFailUpdatedGeneration as json only
* fix: update GrpcBlobReadChannel to match automatic decompression behavior of json
* fix: update GrpcBlobReadChannel to match exception behavior for failed preconditions

test: enable grpc config for ITBlobReadChannelTest

---

google-cloud-storage/pom.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java

Add new builder method to all setting attempt of direct path connection.
If enabled, the underlying gapic client will be configured to attempt connecting via direct path and using client side load balancing.
deps: add a direct dependency to io.grpc:grpc-googleapis
Rumour has it this dependency will be removed from gax, and we need to pull it up to our level to ensure it's there for storage direct path.

feat: add GrpcStorageOptions.Builder#setAttemptDirectPath

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BackwardCompatibilityUtils.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcBlobWriteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Hasher.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Utils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BackwardCompatibilityUtilsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java

Storage#createFrom and Storage#writer allow specifying an explicit crc32c value which should be passed to GCS for validation. Update our uploads to allow these explicitly defined values to be passed in the `finish_write` message to GCS.
Update UnifiedOpts.Crc32cValue to represent its value as an int rather than the b64 string from apiary. Internally when the value is necessary for apiary it will be converted to the b64 string representation.
Map gRPC Status `DATA_LOSS` to HTTP 400 Bad Request to mirror the behavior of JSON when a checksum validation fails.
Add a new Hasher.constant instant which will function to specify a constant value for the cumulative value of a write.
Various plumbing tweaks to allow passing this value all the way down and also attempting to "nullSafeConcat"
Add new …

fix: update Object Write handling to be able to specify an explicit crc32c value

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/IamPolicyPropertyTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITAccessTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/TemporaryBucket.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/IamPolicyArbitraryProvider.java
google-cloud-storage/src/test/resources/META-INF/services/net.jqwik.api.providers.ArbitraryProvider

* fix: fixup ITAccessTest#testRetentionPolicyNoLock to pass for gRPC
* fix: fixup ITAccessTest#testUBLAWithPublicAccessPreventionOnBucket to pass for gRPC
* chore(test): fixup ITAccessTest generic acl and default acl tests to only run for JSON
* fix: fixup ITAccessTest related to Bucket IAM Policy
* chore(test): set ITAccessTest#testBucketWithBucketPolicyOnlyEnabled to json only
* chore(test): set ITAccessTest#testBucketWithUniformBucketLevelAccessEnabled to json only
* chore: fmt
* fix: fixup ITAccessTest#testEnableAndDisableBucketPolicyOnlyOnExistingBucket to work with grpc instance
* fix: fixup ITAccessTest#testEnableAndDisableUniformBucketLevelAccessOnExistingBucket to work with grpc instance
* fix: fixup ITAccessTest#testEnforcedPublicAccessPreventionOnBucket to work with grpc …

test: enable gRPC config for ITAccessTest

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Acl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobId.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Cors.java
google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultStorageRetryStrategy.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcRetryAlgorithmManager.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/HmacKey.java
google-cloud-storage/src/main/java/com/google/cloud/storage/HttpCopyWriter.java
google-cloud-storage/src/main/java/com/google/cloud/storage/HttpMethod.java
google-cloud-storage/src/main/java/com/google/cloud/storage/HttpRetryAlgorithmManager.java
google-cloud-storage/src/main/java/com/google/cloud/storage/HttpStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/NotificationInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Option.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Rpo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ServiceAccount.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageClass.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UniformStorageRetryStrategy.java
google-cloud-storage/src/test/java/com/google/cloud/storage/SerializationTest.java

* Update javadocs on all new @BetaApi methods to state they are preview apis and subject to breaking changes
* Update TransportCompatibility annotations to apply to more classes and methods
* Regenerate all serialVersionUID values to ensure no leaking version numbers compared with other classes

chore: update javadocs, TransportCompatibility and serialVersionUID values ahead of merge to main

---

README.md
google-cloud-storage/src/main/resources/META-INF/native-image/com/google/cloud/storage/native-image.properties
google-cloud-storage/src/test/resources/META-INF/native-image/com/google/cloud/storage/native-image.properties

Running storage tests in GraalVM 22.2.0 results in:
```
Error: Classes that should be initialized at run time got initialized during image building:
com.fasterxml.jackson.core.JsonToken was unintentionally initialized at build time. com.google.api.client.json.jackson2.JacksonParser$1 caused initialization of this class with the following trace: 
at com.fasterxml.jackson.core.JsonToken.<clinit>(JsonToken.java:31)
at com.google.api.client.json.jackson2.JacksonParser$1.<clinit>(JacksonParser.java:121)
```
The root cause was the specification of `com.google.api.client.json` where we were initializing the whole package at build time.  This PR initializes only the necessary classes at build time to resolve this.

fix(java): avoid unexpected initialization of `JacksonParser` in Graal 22.2

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java

fix: Fixing the issue of MatchPrefix and Matchsuffix properties set in the GCP Console not being picked up by the API (BucketInfo).
Fixes #1715  ☕️

fix: update BucketInfo.LifecycleRule#fromPb to wire through MatchesPrefix & MatchesSuffix

---

google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java

Follow up to https://github.com/googleapis/java-storage/pull/1717

test: add tests to cover the MatchesPrefix and MatchesSuffix in LifeCyleRules

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BackwardCompatibilityUtils.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcToHttpStatusCodeTranslation.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BackwardCompatibilityUtilsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GrpcToHttpStatusCodeTranslationTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ResultRetryAlgorithmCompatibilityTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageExceptionGrpcCompatibilityTest.java

Move all mapping from GrpcStorageImpl and BackwardCompatibilityUtils to GrpcToHttpStatusCodeTranslation.
Define new GrpcToHttpStatusCodeTranslation.StatusCodeMapping to explicitly define a mapping between io.grpc.Status.Code and our http code
Update tests to be explicit and not depend on utility methods which can also be used by the code under test.
Add new tests to ensure expected status codes are returned when evaluating DefaultStorageRetryStrategy

chore: refactor and cleanup translation between gRPC status codes and http codes

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketLifecycleRulesTest.java

Add new test class ITBucketLifecycleRulesTest to validate some bucket mutations related to lifecycle rules behave as expected.
Update GrpcConversions to detect an empty list and preserve null value if the value from the server is empty.
New tests cases ported forward related to https://github.com/googleapis/java-storage/pull/1717 and https://github.com/googleapis/java-storage/pull/1724

fix: update BucketInfo.LifecycleRule.LifecycleCondition equals and hashCode to include match prefix and suffix

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcBlobReadChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITReadMaskTest.java

Previously a subbed method was still being used, now it will check the lazy channel.
Removed duplicate memoization of channel factory
* chore: update assertion for possible RPO values via gRPC

fix: properly implement GrpcBlobReadChannel#isOpen

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketTest.java
samples/snippets/src/main/java/com/example/storage/bucket/GetBucketAutoclass.java
samples/snippets/src/main/java/com/example/storage/bucket/SetBucketAutoclass.java
samples/snippets/src/test/java/com/example/storage/bucket/AutoclassTest.java

https://github.com/googleapis/java-storage/issues/1598
Adds support and samples for Autoclass

feat: add Autoclass support and sample

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/PackagePrivateMethodWorkarounds.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java

Update GrpcStorageImpl#get(BlobId) to match the behavior of StorageImpl#get(BlobId) and return a null values when 404 is encountered.

fix: update GrpcStorageImpl#get(BlobId) to return null on 404

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageFixture.java
google-cloud-storage/src/test/java/com/google/cloud/storage/UnifiedOptsTest.java

Update all option factory methods to explicitly state their Nullability bounds. All methods which take non-primitive parameters are @NonNull, and will be published in the javadocs.
Add new tests to explicitly verify null argument validation.
All factory methods now check their args for nullness, instead of depending on implicit checking.

docs: annotate all Option factory methods with their Nullability bounds

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITAccessTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketLifecycleTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/StorageInstance.java

Some tests have not been properly cleaning up buckets and leaking resources outside the suite.
Cleanup of existing leaked buckets will be handled separately.

test: fix bucket cleanup logic

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageV2ProtoUtils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/TestUtils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITAccessTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketAclTest.java

Newly implemented methods (including any overloads):
1. GrpcStorageImpl#createAcl
2. GrpcStorageImpl#getAcl
3. GrpcStorageImpl#listAcl
4. GrpcStorageImpl#updateAcl
5. GrpcStorageImpl#deleteAcl
6. Bucket#createAcl
7. Bucket#getAcl
8. Bucket#listAcl
9. Bucket#updateAcl
10. Bucket#deleteAcl

feat: implement GrpcStorageImpl BucketAccessControl operations

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITAccessTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectAclTest.java

Newly implemented methods (including any overloads):
1. GrpcStorageImpl#createAcl
2. GrpcStorageImpl#getAcl
3. GrpcStorageImpl#listAcl
4. GrpcStorageImpl#updateAcl
5. GrpcStorageImpl#deleteAcl
6. Blob#createAcl
7. Blob#getAcl
8. Blob#listAcl
9. Blob#updateAcl
10. Blob#deleteAcl

feat: implement GrpcStorageImpl ObjectAccessControl operations

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUploadSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Hasher.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ResumableWrite.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/main/java/com/google/cloud/storage/WriteFlushStrategy.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GapicUnbufferedWritableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/TestUtils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectChecksumSupportTest.java

Remove Hasher.Constant. StartResumableWriteRequest has been updated to allow specifying `object_checksums` when creating the session.
Add several new positive and negative integration test for md5 verification

fix: update Grpc Write implementation to allow specifying expected md5

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITAccessTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/AbstractStorageProxy.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/StorageInstance.java

Simplify StorageInstance vetoing implementation. Rather than using a runtime proxy to do invocation method argument matching we are now defining a concrete class to override the methods it needs to provide enforcement for.
This is simpler in that it uses standard java language implementation approach which is helped by compiler and IDEs. It is at the expense of needing to define the new ~500 line AbstractStorageDecorator class.
Delete several obsolete tests, which have been replace by other tests or do not make sense to be written the way they are.
Cleanup of TODO from https://github.com/googleapis/java-storage/pull/1785

chore(test): expand StorageInstance vetoing to apply to bucket acl operations

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITKmsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java

While re-enabling several gRPC excluded tests after backend fixes clearing a buckets logging config via gRPC wasn't working.
* test: re-enable several gRPC excluded tests after backend fixes

fix(grpc): fix bucket logging conversion to allow clearing

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/StorageITRunner.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/annotations/CrossRun.java

Update initialization logic of StorageITRunner to by default disallow use of @ClassRules. Add new annotation @CrossRun.AllowClassRule to allow use of a rule in the event it may be necessary.
Cleanup of TODO from https://github.com/googleapis/java-storage/pull/1785

test: update StorageITRunner behavior along with @ClassRule

---

google-cloud-storage/pom.xml
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITKmsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/BackendResources.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/KmsFixture.java
renovate.json

Add new `KmsFixture` class to encapsulate and pull the lifecycle of the Kms `KeyRing` and `Keys` up into the Registry.
Remove all KMS/IAM related setup from ITKmsTest in favor of the new Fixture.
Drop use of grpc stubs directly in favor of the GAPIC client for KMS.
Cleanup of TODO from https://github.com/googleapis/java-storage/pull/1785

test: introduce KmsFixture

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadChannelV2RetryTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobWriteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketLifecycleRulesTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITGrpcTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectAclTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectChecksumSupportTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/Generator.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/Registry.java

In order to facilitate running tests in parallel, even across configurations object names need to be unique to a test. This new method encapsulates reliably generating test unique object names.
Generated tests names will look of the form: `testName[HTTP][PROD]-0001`
Replace usages of `TestName#getMethodName()` with `Generator#randomObjectName()`

test: add new Generator#randomObjectName

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITKmsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java

Rework list centric tests in ITObjectTest to have more straightforward implementations and assertions, and in some cases a more clear name of what is being validated. (Removed all the list retry stuff, object list is strongly consistent in GCS.)

fix: update gRPC object list implementation to include synthetic directories

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITAccessTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketIamPolicyTest.java

Update ITAccessTest to run UBLA and IAM centric tests for gRPC. Split iam v1 and iam v3 tests out from ITAccessTest to ITBucketIamPolicyTest making them hermetic.

docs: document differing behavior of {get,list}{,default}Acl between HTTP and gRPC

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITAccessTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBatchTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITDownloadBlobWithoutAuth.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITDownloadToTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITKmsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITSignedUrlTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITWriteChannelConnectionPoolTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/StorageITLeafRunner.java

Follow up to #1826 
Migrate tests which previously had hard coded object names to use new `Generator#randomObjectName()`.
Serval test which were previously using `@Rule Timeout` or `@Test(timeout = N)` have had their timeouts removed. The Timeout implementation in JUnit 4 is not thread safe, and can result in running test tracking issues.
The majority of these tests have had their timeouts made completely obsolete in #1824 and their change here will be short lived.
Each commit in this PR is migrating a single IT class.

test: migrate tests which previously had hard coded object names to use new Generator#randomObjectName()

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketReadMaskTest.java

A fix is being rolled out on the backend, where sometimes grpc will return values.

chore(test): update assertion for ITBucketReadMaskTest[DEFAULT_OBJECT_ACL]

---

google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/ITRetryConformanceTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RetryTestFixture.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/TestRetryConformance.java
google-cloud-storage/src/test/resources/com/google/cloud/storage/conformance/retry/hello-world.txt

Update method mappings to properly exclude retry conformance tests for Bucket#create.
Update TestRetryConformance to lazily allocate and fill a temporary file when necessary.

test: enable S.7 retry conformance tests

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ByteRangeSpec.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ByteRangeSpecTest.java

There are some cases where endOffset and endOffsetInclusive are both necessary and externally being able to differentiate is needed.
As part of this change, I've update the declaration of ByteRangeSpec.RangeScenario to be more verbose and easier to read, as well as have a more direct description for the test name.
This does add a fair number of lines of code, but I think it brings some clarity compared to a method with 4 different long arguments. It also reduces (and possible errors in declaration) between related scenarios.
In general the new pattern is: define the four properties of any range (beginOffset, endOffset, endOffsetInclusive, length) then specify those ByteRangeSpecs for which it should be applicable.

chore: introduce ByteRangeSpec#endOffsetInclusive

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BaseStorageReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobReadChannelV2.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ByteRangeSpec.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcBlobReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageV2ProtoUtils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ByteRangeSpecTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageV2ProtoUtilsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadChannelTest.java

Extract the majority of BlobReadChannelV2 to a new abstract base class BaseStorageReadChannel which effectively adapts a LazyReadChannel to a StorageReadChannel.
BaseStorageReadChannel now defines an abstract method newLazyReadChannel which each implementation is responsible for implementing to integrate into the lifecycle.

feat: update GrpcBlobReadChannel to allow seek/limit after read

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketLifecycleRulesTest.java

Zero (0) is a special value for some serialization configurations. Add a test to ensure it is properly passed to the backend, and is effective.

test: add test to verify `lifecycle.rule.condition.age_days = 0`

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BaseStorageReadChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadChannelTest.java

Add two new tests to verify new expected close behavior surfaced from java-storage-nio.

fix: update BaseStorageReadChannel to be left open unless explicitly closed

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryUnbufferedReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BaseStorageReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobReadChannelV2.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcBlobReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/HttpDownloadSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/LazyReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Utils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/LazyReadChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/PackagePrivateMethodWorkarounds.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageReadChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/ObjectsFixture.java

Publicly exposing this is gated on how/when we are able to expose StorageReadChannel.

chore: refactor BlobReadChannel to plumb the sparse object metadata included in a read media response for both json and grpc

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryUnbufferedReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BaseStorageReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobReadChannelV2.java
google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultBufferedReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicDownloadSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GzipReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/HttpDownloadSessionBuilder.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadChannelV2RetryTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/TestBench.java

When downloading bytes from gcs and decompressing them, a restart of the stream needs to pickup from the offset within the compressed bytes not the decompressed bytes.
Prior to this change http-client was automatically applying gzip decompression to the stream it returns to us thereby causing our tracking to be off.
This change updates our interaction with http client to always request the raw bytes without any transform applied to them, we then at a higher level can handle whether gzip decompression needs to be plumbed in.
Fix up a couple channel closed state subtleties when buffering is used with decompression.
Add a new test leveraging the testbench which forces a broken stream on some compressed object bytes. _NOTE_ This test depends on the next release of testbench and will be …

fix: update BlobReadChannelV2 handling to correctly restart for decompressed object

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
samples/snippets/src/main/java/com/example/storage/object/UploadObject.java

* com.google.cloud.storage.Storage.BlobWriteOption.generationMatch(long)
* com.google.cloud.storage.Storage.BlobWriteOption.generationNotMatch(long)
* com.google.cloud.storage.Storage.BlobWriteOption.metagenerationMatch(long)
* com.google.cloud.storage.Storage.BlobWriteOption.metagenerationNotMatch(long)
Update UploadObject sample to use createFrom rather than trying to read the entire file into memory.

feat: add Storage.BlobWriteOption.{meta,}generation{Not,}Match(long) methods to allow literal value construction

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadJob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadResult.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ParallelDownloadConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ParallelUploadConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManager.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferStatus.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadJob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadResult.java

feat: Initial Classes and Interface for Transfer Manager

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/BackendResources.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/ObjectsFixture.java

Sometimes it's useful to specify that the ObjectsFixture should use the RequesterPays bucket
This change is needed from a followup PR which performs some operations on a requester pays bucket, but itself does not need to create objects.

test: update ObjectsFixture to allow discrimination by @BucketFixture

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/test/java/com/google/cloud/storage/TransportCompatibilityTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITQuotaProjectIdTest.java

Add integration tests to verify desired precedence when resolving userProject options.
Fixes #1736

fix: update GrpcStorageImpl handling to be aware of quotaProjectId

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannelTest.java

Cumulative crc32c check is only applicable to an initial offset of 0 because the crc32c value return for a resource is for the entire resource. Instead, we continue to perform the crc32c integrity check for each ChecksummedData which is always for the bytes it is packed with.

chore: remove cumulative crc32c check on GapicUnbufferedReadableByteChannel

---

google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultStorageRetryStrategy.java
google-cloud-storage/src/test/java/com/google/cloud/storage/DefaultRetryHandlingBehaviorTest.java

Update Default RetryStrategy to retry when an SSLException is caused by a SocketException

fix: update Default RetryStrategy to retry SSLException caused by SocketException

---

google-cloud-storage/pom.xml
google-cloud-storage/src/test/java/com/google/cloud/storage/it/StorageNativeCanary.java
google-cloud-storage/src/test/resources/META-INF/native-image/com/google/cloud/storage/native-image.properties
google-cloud-storage/src/test/resources/META-INF/native-image/com/google/cloud/storage/reflect-config.json

Update native-image related config to be specific for this class.
Update maven config to explicitly configure this new class as it's only class for test when run under -Pnative
Prior this change, the native image pre-submit builds will run the full integration test suite 2 times, 1 time to discover the tests which should be run during `native-test` and then again run during `native-test`.
We don't need the whole integration suite ran multiple times, or even to verify native image has built a working program. Instead, we have a specific scenario which exercises all possible request types ensuring each request type is covered. This new CanaryTest runs everything in ~30 seconds, whereas the full integration suite is ~13 min on current CI machines.

test: add new StorageNativeCanaryTest

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITAccessTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketLifecycleRulesTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketLifecycleTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITKmsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITNestedUpdateMaskTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java

When b/270215524 is fixed and rolled out we should be able to revert this

chore: ignore Update related gRPC tests which are failing due to b/270215524

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BaseStorageReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ByteRangeSpec.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageReadChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ByteRangeSpecTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadChannelTest.java

GCS Supports negative offsets in ranged reads and is documented in https://cloud.google.com/storage/docs/json_api/v1/parameters#range
Update the ReadChannel returned from Storage.reader to allow providing a negative value to `seek`.
NOTE: `seek` to a negative offset will be ignored by GCS if `limit` is also specified

feat: allow specifying a negative offset to ReadChannel

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java

Adds a note about non-editable metadata to all CreateBlob documentation. This addresses internal bug 273252496.

docs: add clarification on non-editable metadata

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadCallable.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadJob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadCallable.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITTransferManagerTest.java

feat: First pass downloadMany

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/TestBench.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/BucketArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/StorageArbitraries.java

Creation of a bucket is modifying which field is used to specify the project a bucket is associated with. Changing from `parent` to `bucket.project`. This change updates our handling to use this new field.
The existing `parent` is set to the sentinel value `projects/_` which was previously only implicitly found in the bucket name.
Update testbench tag to v0.35.0 which includes the new field behavior.
ApiaryConversions have been updated to track the project attribute when cross converting as the property `.x_project`; this value should avoid any possible collision if the field name project is supported in the future while the client is operating in this intervening time. If/when StorageObject receives its own project field we should switch to using it.
Fix associated with b/254678990
This …

fix: update bucket creation to set project as `bucket.project`

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadCallable.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITTransferManagerTest.java

Small PR to add BlobWriteOptions to UploadMany operations, for downloadMany this was included in the first pass but was left out of the first pass for UploadMany. 
See: https://github.com/googleapis/java-storage/pull/1945

feat: Apply BlobWriteOptions to UploadMany operations

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Notification.java
google-cloud-storage/src/main/java/com/google/cloud/storage/NotificationInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Utils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/NotificationInfoPropertyTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITNotificationTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/NotificationArbitraryProvider.java
google-cloud-storage/src/test/resources/META-INF/services/net.jqwik.api.providers.ArbitraryProvider

Rewrite ITNotificationTest to leverage testbench for grpc and to separate different cases into their own individual tests rather than having a single large test.
For now the backend hasn't yet implemented the rpcs for grpc, so we rely on testbench. Once the backend does provide we can remove the `CrossRun.Ignore` annotation on each of the methods.

feat: implement GrpcStorageImpl#{get,list,create,delete}Notification

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobId.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobIdTest.java

feat: Handle generation numbers in BlobId#{to,from}GsUtilUri

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplMockitoTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java

This is a new feature (b/236167515) where List Objects allows filtering results based on a provided glob pattern.
Currently only the JSON API supports the matchGlob parameter, so using the option with gRPC will throw an exception. gRPC support is planned for later.

feat: Add matchGlob parameter to BlobListOption

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadCallable.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadJob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ParallelDownloadConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ParallelUploadConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerUtils.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadCallable.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadJob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadResult.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITTransferManagerTest.java

Changes from review session with @BenWhitehead 
Summary of changes:
- Make public classes private
- Remove array creation from callable to reduce multiple threads creating options array
- Change generic future to be ApiFuture
- Add documentation to configs
- Have tests await task completion
- Check to make sure directories have been created before attempting to write a file on download

fix: Review session updates

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BaseStorageReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobReadChannelV2.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcBlobReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/LazyReadChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/LazyReadChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageReadChannelTest.java

For some scenarios, an external client needs the ability to manage buffer blocking itself. To support this, providing 0 to ReadChannel#setChunkSize will disable buffering allowing for client to avoid the need to alight multiple levels of buffer alignments.
Because the buffering is disabled, that means reads can be much more variable in size and individually more impacted by small network latencies (with buffering these can be amortized by the buffer making followup read faster). This is considered advanced usage and will require more work from the client integrator.

feat: make it possible to disable the buffer of ReadChannels returned from Storage.reader

---

google-cloud-storage/src/test/java/com/google/cloud/storage/ITGapicReadTimeoutTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGapicUnbufferedReadableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGapicUnbufferedWritableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGrpcStorageImplUploadRetryTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGzipReadableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITUpdateMaskTest.java

GitHub actions seem to sometimes have issues with tcp connection's lingering longer than they should, or having things delayed. Other languages have encountered TCP issues in their actions too.
In an effort to try and reduce the likelihood of this causing build flakiness move these test which use FakeServer to be Integration tests where we haven't encountered these kinds of failures.
Fixes #1748

chore: move tests which use FakeServer to be Integration Tests

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobId.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobIdTest.java

When BlobId#toGsUtilUri was updated to output generation if defined, this broken older clients ability to parse the value via BlobId#fromGsUtilUri. This adds the new method toGsUtilUriWithGeneration to explicitly opt in to generation being okay in the output.
Related to #1928
Related to #1929

fix: introduce new BlobId#toGsUtilUriWithGeneration

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ChunkedDownloadCallable.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DefaultQos.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DirectDownloadCallable.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadJob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadResult.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadSegment.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/Qos.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManager.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerUtils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITTransferManagerTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/transfermanager/TransferManagerConfigTestingInstances.java

feat: Implement chunkedDownload and refactor direct downloads.

---

google-cloud-storage/src/main/java/com/google/cloud/storage/PackagePrivateMethodWorkarounds.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DirectDownloadCallable.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadResult.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadCallable.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITTransferManagerTest.java

feat: Error handling for Downloads

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITTransferManagerTest.java

If we are unable to get information about a blob (ie. if the get call fails) we should still try and download the blob but we can simply do a direct download. This actually was causing the integration tests to fail with an NPE however in previous PRs these tests were not configured to run.

fix: validateBlob failure fallsback to direct download

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadJob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadJob.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITTransferManagerTest.java

For the public API we will resolve the API Futures and return the result (ie. await the resolution and return the result).

feat: Resolve API futures on getDownload/UploadResults calls

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Option.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/DedupeOptionTest.java

When providing options duplicates are not allowed, however there are times when you might end up providing two options which would collide. These new utility methods encapsulate the logic necessary to deduplicate any overlap wil returing an array which can be passed directly to the respective operation method.
`dedupe` utility methods added to each of the following Option classes:
* Storage.BlobGetOption.dedupe();
* Storage.BlobListOption.dedupe();
* Storage.BlobSourceOption.dedupe();
* Storage.BlobTargetOption.dedupe();
* Storage.BlobWriteOption.dedupe();
* Storage.BucketGetOption.dedupe();
* Storage.BucketListOption.dedupe();
* Storage.BucketSourceOption.dedupe();
* Storage.BucketTargetOption.dedupe();
* Storage.CreateHmacKeyOption.dedupe();
* Storage.DeleteHmacKeyOption.dedupe();
* …

feat: add new dedupe utility method to Option classes

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/SneakyException.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/TestBench.java
google-cloud-storage/src/test/resources/com/google/cloud/storage/it/runner/registry/Dockerfile

Renovate-bot does not look into java files for docker images. Add a Dockerfile into our test resources that is loaded on TestBench class initialization.

chore: attempt to make TestBench docker image renovateable

---

google-cloud-storage/src/main/java/com/google/cloud/storage/PackagePrivateMethodWorkarounds.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ParallelUploadConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadCallable.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITTransferManagerTest.java

This PR has a few parts to it, all small enough to where I did not feel the need to separate.
There was a bug where the storageObject was being accessed before the WriteChannel closes, when the upload is not finished WriteChannel returns a null storageObject resulting in an NPE when we go to decode the storageObject. see [BlobWriteChannel#storageObject](https://github.com/googleapis/java-storage/blob/976b9ba367d5eb5bcd4a2b50ef6f530b3a6dff94/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java#L44) for where this is documented.
First Pass (up to commit [76462df](https://github.com/googleapis/java-storage/pull/2086/commits/76462df4649db6764043f1ca011e5d2d62a68ddd)): addressed this by trying to process the storageObject outside of the scope of the try block, …

fix: update UploadCallable to use createFrom to avoid NPE trying to resolve resulting object

---

samples/snippets/src/main/java/com/example/storage/bucket/DisableDefaultEventBasedHold.java
samples/snippets/src/main/java/com/example/storage/bucket/DisableLifecycleManagement.java
samples/snippets/src/main/java/com/example/storage/bucket/DisableUniformBucketLevelAccess.java
samples/snippets/src/main/java/com/example/storage/bucket/EnableDefaultEventBasedHold.java
samples/snippets/src/main/java/com/example/storage/bucket/EnableUniformBucketLevelAccess.java
samples/snippets/src/main/java/com/example/storage/bucket/RemoveBucketDefaultKmsKey.java
samples/snippets/src/main/java/com/example/storage/bucket/SetBucketDefaultKmsKey.java
samples/snippets/src/main/java/com/example/storage/bucket/SetRetentionPolicy.java
samples/snippets/src/test/java/com/example/storage/ITBucketSnippets.java
samples/snippets/src/test/java/com/example/storage/TestUtils.java
samples/snippets/src/test/java/com/example/storage/TestUtilsTest.java

When asserting a bucket update has taken place, sometime there can be a lag between when the update RPC succeeds and when it actually takes effect. Update our test assertions to retry if they fail up to a configured maximum duration.
Fixes #2060
Fixes #2068
Fixes #2069
Fixes #2070

test(samples): update ITBucketSnippets to apply retries to update result assertions

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ParallelDownloadConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ParallelUploadConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManager.java

First commit for Javadocs. Will continue to add files as I write them but wanted to get initial feedback to ensure this is the direction we would like the javadocs to go and they are clear.

docs: Javadocs for TransferManager interface and ParallelUploadConfig

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ByteRangeSpec.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ByteSizeConstants.java
google-cloud-storage/src/main/java/com/google/cloud/storage/HttpClientContext.java
google-cloud-storage/src/main/java/com/google/cloud/storage/HttpContentRange.java
google-cloud-storage/src/main/java/com/google/cloud/storage/HttpStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSession.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSessionFailureScenario.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSessionPutTask.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSessionQueryTask.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableWrite.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ResumableOperationResult.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ResumableSession.java
google-cloud-storage/src/main/java/com/google/cloud/storage/RewindableHttpContent.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/FakeHttpServer.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITJsonResumableSessionPutTaskTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITJsonResumableSessionQueryTaskTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITJsonResumableSessionTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/JsonResumableSessionFailureScenarioTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/RewindableHttpContentPropertyTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplMockitoTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/Functions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/ITRetryConformanceTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectChecksumSupportTest.java

When uploading a file where we are able to rewind to an arbitrary offset, we can be more optimistic in the way we send requests to GCS.
Add new code middleware to allow PUTing an entire file to GCS in a single request, and using query resumable session to recover from the specific offset in the case of retryable error.
Generate a random file on disk of size `128KiB..2GiB` from `/dev/urandom`, then upload the generated file using `Storage.createFrom(BlobInfo, Path)`.
Perform each 4096 times.
Run on a c2-standard-60 instance is us-central1 against a regional bucket located in us-central1.
The following summary of throughput in MiB/s as observed between the existing implementation, and the new implementation proposed in this PR.
```
count     mean     std    min      50%      75%      90% …
```

feat: update Storage.createFrom(BlobInfo, Path) to have 150% higher throughput

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryUnbufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ByteSizeConstants.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicWritableByteChannelSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcResumableSession.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSession.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSessionPutTask.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ResumableSession.java
google-cloud-storage/src/main/java/com/google/cloud/storage/RewindableContent.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/FakeHttpServer.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGrpcStorageImplUploadRetryTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITJsonResumableSessionPutTaskTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITJsonResumableSessionTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/RewindableByteBufferContentTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/RewindableContentPropertyTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectChecksumSupportTest.java

With the introduction of RewindableContent, we can now upload an entire file in a single WriteObjectRequest stream.
* chore: rename RewindableHttpContent -> RewindableContent

fix: update GrpcStorageImpl.createFrom(BlobInfo, Path) to use RewindableContent

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryUnbufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannelV2.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSessionPutTask.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableWrite.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITJsonResumableSessionTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/SerializationTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobWriteChannelTest.java

The tests in ITObjectTest did not perform a flush before capturing the write channel and this flow was not previously validated.

fix: update BlobWriteChannelV2 to properly carry forward offset after incremental flush

---

TESTING.md
google-cloud-storage/src/main/java/com/google/cloud/storage/testing/package-info.java

docs: fix broken link for TESTING.md

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java

There are some scenarios where application default credentials resolution results in `null`.
Add an explicit check to provide a more useful error message than NullPointerException.

fix(grpc): return error if credentials are detected to be null

---

pom.xml

Now that shared-dependencies is tracking grpc 1.56.1 we no longer need to override it ourselves.

chore: remove manual grpc version management

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteSessionConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultBlobWriteSessionConfig.java

BlobWriteSessionConfig needs to implement Serializable because it plugs into StorageOptions which is Serializable.
Not sure, how the SerializationTest was passing when the PR was posted and now fails on main.

chore: update BlobWriteSessionConfig to implement Serializable

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryUnbufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultBufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultStorageRetryStrategy.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcResumableSession.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageByteChannels.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnbufferedWritableByteChannelSession.java
google-cloud-storage/src/test/java/com/google/cloud/storage/DefaultBufferedWritableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGapicUnbufferedWritableByteChannelTest.java

Add new methods to UnbufferedWritableByteChannel to allow writing and closing in a single call
* writeAndClose(ByteBuffer)
* writeAndClose(ByteBuffer[])
* writeAndClose(ByteBuffer[], int, int)
Update grpc and json implementation to leverage new methods and to write and finalize in the same call.
DefaultBufferedWritableByteChannel will use the new methods as appropriate.

fix: optimize resumable uploads to allow sending bytes during finalization

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Throughput.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ThroughputMovingWindow.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ThroughputSink.java
google-cloud-storage/src/test/java/com/google/cloud/storage/TestClock.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ThroughputMovingWindowPropertyTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ThroughputSinkTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ThroughputTest.java

_Pre-work_
In some upcoming work we want to be able to keep a running window of throughput performance in order to provide improved throughput. This PR introduces a new utility class to model and compute throughput, and the concept of a ThroughputSink which values can be appended to.

chore: introduce Throughput and ThroughputSink

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteSessionConfigs.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BufferToDiskThenUpload.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/RecoveryFile.java
google-cloud-storage/src/main/java/com/google/cloud/storage/RecoveryFileManager.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageInternal.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ThroughputSink.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BufferToDiskThenUploadTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/RecoveryFileManagerTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/SerializationTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobWriteSessionTest.java

There are scenarios in which disk space is more plentiful than memory space. This new BlobWriteSessionConfig allows augmenting an instance of storage to prefer buffering to disk rather than keeping things in memory.
Once the file on disk is closed, the entire file will then be uploaded to GCS.

feat: implement BufferToDiskThenUpload BlobWriteSessionConfig

---

google-cloud-storage/src/main/java/com/google/cloud/storage/HttpStorageOptions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/SerializationTest.java

Java can dedupe objects in a cyclic traversal, retryingDepsAdapter doesn't need to be transient.
b/294399427

fix: possible NPE when HttpStorageOptions deserialized

---

google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java

`buildOrThrow` was added in guava 31.0, and while we specify a min version >= 31.0, sometimes our library is used in environments that set different guava version (usually due to platform pinned versions).
We do not strictly need this method, as it has the same behavior of `ImmutableMap.Builder#build()` but with a more clear name (`ImmutableMap.Builder` never allowed duplicate keys).
Manually tested, but creating a separate project that did the following in its maven config:
```
<dependencyManagement>
<dependencies>
<dependency>
<groupId>com.google.guava</groupId>
<artifactId>guava</artifactId>
<version>24.0-jre</version>
</dependency>
<dependency>
<groupId>com.google.cloud</groupId>
<artifactId>google-cloud-storage-bom</artifactId>
<version>2.26.1-SNAPSHOT</version>
<type>pom</type> …
```

fix: make use of ImmutableMap.Builder#buildOrThrow graceful

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/WriteFlushStrategy.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGapicUnbufferedWritableByteChannelTest.java

As of 2.26.0 it would set finish_write on every message emitted by writeAndClose
Update ITGapicUnbufferedWritableByteChannelTest to also include checksum values in its requests/responses.

fix: update gRPC writeAndClose to only set finish_write on the last message

---

google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITUserAgentTest.java

The apiary library manually injects ApplicationName into each request it constructs. For resumable uploads (start and PUTs) we are using the apiary clients http client directly. Update our registered interceptor to add the user-agent if it is null.
Fixes b/294437023

fix: update User-Agent handling for resumable uploads

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerImpl.java

Update StorageOptions to resolve its version from maven metadata rather than manifest version. A jar can only have one MANIFEST.mf thereby leading to storage thinking it is a version it is not.
In particular, if a program is shaded, this change will now allow for the actual version of storage to be carried through.
Related https://github.com/googleapis/google-api-java-client/pull/1419

fix: update version resolution logic to be more resilient

---

samples/snippets/src/test/java/com/example/storage/QuickstartSampleIT.java

The current bucket name doesn't have an allowlisted prefix so the test is failing. Use the allowlisted prefix for now.
Fixes #2174
Fixes #2175

test: update bucket name for gRPC quickstart

---

google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSessionFailureScenario.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSessionQueryTask.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITJsonResumableSessionQueryTaskTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/JsonResumableSessionFailureScenarioTest.java

According to https://cloud.google.com/storage/docs/performing-resumable-uploads#status-check a 308 response that does not contain a Range header should interpret as GCS having received no data.
Include x-goog-gcs-idempotency-token in Json Resumable upload debug context

fix: a resumable session without a Range header should be interpreted as 0 length

---

storage-shared-benchmarking/src/main/java/com/google/cloud/storage/benchmarking/StorageSharedBenchmarkingCli.java
storage-shared-benchmarking/src/main/java/com/google/cloud/storage/benchmarking/W1R3.java

1. Rename Workload1.java to W1R3 to prevent future confusion when it is used for other workloads
2. Take in temporary directory as a CLI argument
3. Utilize PrintWrite instead of System.out directly

feat: Follow-up CLI Improvements

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteSessionConfigs.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Buffers.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ChunkSegmenter.java
google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultBlobWriteSessionConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultBufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicWritableByteChannelSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JournalingBlobWriteSessionConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/RecoveryFile.java
google-cloud-storage/src/main/java/com/google/cloud/storage/RecoveryFileManager.java
google-cloud-storage/src/main/java/com/google/cloud/storage/SyncAndUploadUnbufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/SyncingFileChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ThroughputSink.java
google-cloud-storage/src/main/java/com/google/cloud/storage/WriteCtx.java
google-cloud-storage/src/main/java/com/google/cloud/storage/WriteFlushStrategy.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITSyncingFileChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/RewindableContentPropertyTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/TestUtils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ThroughputSinkTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITGrpcInterceptorTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITJournalingBlobWriteSessionConfigTest.java

New BlobWriteSessionConfig that will use disk to "Journal" data before transmitting to GCS.
By journaling the data to disk we can rewind to an arbitrary offset in the case of failure, while being optimistic and keeping the stream open to gcs.
General flow of data into this new WritableByteChannel:
1. #write(ByteBuffer)
2. Write contents of ByteBuffer to recovery file on disk
3. force a flush to disk
4. transmit contents of ByteBuffer to GCS leaving stream open
5. return
If the stream to gcs is interrupted with a retriable error
1. query the offset that was successfully committed to GCS
2. rewind our transmit context to the offset
3. Open the recovery file at offset from query
4. stream contents from recovery file to GCS leaving stream open
5. Once recovery file contents are transmitted to …

feat: add new JournalingBlobWriteSessionConfig usable with gRPC transport

---

storage-shared-benchmarking/src/main/java/com/google/cloud/storage/benchmarking/StorageSharedBenchmarkingUtils.java
storage-shared-benchmarking/src/main/java/com/google/cloud/storage/benchmarking/W1R3.java

The cli previously was reporting 0 for throughput. There was some loss between moving from longs and doubles. Also looking at other languages, it appears throughput is being recorded in seconds. We will follow suit.

chore(benchmarking): Fix throughput conversion issue and report metrics in seconds

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcRetryAlgorithmManager.java
google-cloud-storage/src/main/java/com/google/cloud/storage/HttpRetryAlgorithmManager.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java

Update logic to consider an object delete request to be idempotent if the objects generation is specified in the BlobId.

fix: consider Storage#delete(BlobId) idempotent when id has generation

---

google-cloud-storage/src/main/java/com/google/cloud/storage/RecoveryFileManager.java
google-cloud-storage/src/test/java/com/google/cloud/storage/RecoveryFileManagerTest.java

When creating a new recovery file it is important that distinct recovery files be created always, even if the provided BlobInfo is equivalent to a previously created one.
Allocate a UUID, and hash it with goodFastHash(64) before encoding to base64 (url safe).
Follow up to #2195 todo

fix: update RecoveryFileManager to allow distinct files for multiple invocations of equivalent info

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ApiFutureUtils.java
google-cloud-storage/src/main/java/com/google/cloud/storage/AsyncAppendingQueue.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ApiFutureUtilsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/AsyncAppendingQueueTest.java

__Pre-Work__
When performing a parallel composite upload the various object parts need to be stitched together in sequence.
AsyncAppendingQueue allows enqueuing elements that result in some value, and can then be compacted once a certain number of elements are reached (or complete).

chore: add AsyncAppendingQueue

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ApiFutureUtils.java
google-cloud-storage/src/main/java/com/google/cloud/storage/AsyncAppendingQueue.java
google-cloud-storage/src/main/java/com/google/cloud/storage/MetadataField.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ApiFutureUtilsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/AsyncAppendingQueueTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/MetadataFieldTest.java

_Pre-Work_
When performing a parallel composite upload the various parts will have metadata added to them related to where they exist in the overall object.
This class encapsulates the logic necessary to allow defining a field by its name and a codec for encoding/decoding its values.

chore: add MetadataField

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadBlobWriteSessionConfig.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ParallelCompositeUploadBlobWriteSessionConfigTest.java

_Pre-work_
Add skeleton of config parameters available for Parallel Composite Uploads
Javadocs for the new config class will be more flushed out in a following PR

chore: add ParallelCompositeUpload related config

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BufferHandlePool.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BufferHandlePoolTest.java

_Pre-Work_
Provide a pool abstraction for BufferHandles allowing retrieval and returning of BufferHandles rather than direct allocation.

chore: add BufferHandlePool

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadBlobWriteSessionConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/RewindableContent.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageInternal.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BufferToDiskThenUploadTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ParallelCompositeUploadBlobWriteSessionConfigTest.java

_Pre-Work_
Add two new method to StorageInternal for access by new BlobWriteSession implementations
1. `#delete(BlobId)`
2. `#internalDirectUpload(BlobInfo, Opts<ObjectTargetOpt>, ByteBuffer)`

chore: add StorageInternal#{delete(BlobId),internalDirectUpload}

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobId.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Buffers.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Crc32cValue.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadException.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageInternal.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ParallelCompositeUploadWritableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/UnifiedOptsTest.java

_Pre-Work_
Add new ParallelCompositeUploadWritableByteChannel which allows calls to `write` which will automatically break the stream into part objects, uploading each part in the background.
Error handling and validation is implemented with several tests (The majority of this PR is tests, as inducing some of the failures is rather involved).
Automatic cleanup in the case of failure will be implemented in a follow up pr.

chore: add ParallelCompositeUploadWritableByteChannel

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageInternal.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ParallelCompositeUploadWritableByteChannelTest.java

I'm not 100% happy with how invasive this change was, I think we can refactor things after this initial implementation to make it easier to tests and understand.

chore: implement automatic cleanup on failure in ParallelCompositeUploadWritableByteChannel

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteSessionConfigs.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadBlobWriteSessionConfig.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITParallelCompositeUploadBlobWriteSessionConfigTest.java

Expose public api to allow selection and configuration of new Parallel Composite Upload BlobWriteSession strategy

feat: add @BetaApi BlobWriteSession#parallelCompositeUpload

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteSessionConfigs.java

The considerations column being last is cut off in the ultimate rendered javadocs. Move it left before retries and apis used.

docs: reorder columns in table of BlobWriteSessionConfigs.java

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadBlobWriteSessionConfig.java
google-cloud-storage/src/test/java/com/google/cloud/storage/SerializationTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITParallelCompositeUploadBlobWriteSessionConfigTest.java

Use a more clear name to signal the configuration is for the allocation of buffers, not the buffering itself.

chore: rename BufferStrategy to BufferAllocationStrategy

---

google-cloud-storage/src/test/java/com/google/cloud/storage/ITStorageLifecycleTest.java

Looking at CI logs I noticed grpc was logging a leaked channel pool. The storage instance wasn't being closed in these tests.

test: ensure Storage instances are closed in ITStorageLifecycleTest

---

samples/snippets/src/main/java/com/example/storage/bucket/GetBucketAutoclass.java
samples/snippets/src/main/java/com/example/storage/bucket/SetBucketAutoclass.java
samples/snippets/src/test/java/com/example/storage/bucket/AutoclassTest.java

Depends on https://github.com/googleapis/java-storage/pull/2258

chore(samples): update Autoclass Sample for v2.1 features

---

google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/ITRetryConformanceTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RetryTestFixture.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/TestRetryConformance.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobWriteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/TestBench.java

* Current test case resolver still only resolves HTTP cases
* RetryTestFixture is updated to turn a `501 Not Implemented` into an AssumptionViolationException signaling the test is skipped/ignored
* RetryTestFixture is updated to call close on Storage instances -- needed so we don't leak channel builders with grpc
* RetryTestFixture nonTestStorage will always be HTTP, only testStorage will be built with the selected transport
* TestRetryConformance generated names now include either `_h` or `_g` depending on transport -- this removes collisions of names between the two transports
* TestRetryConformance will now generate test names of the following format: `TestRetryConformance/{lower_transport}-{scenario_id}-[{instructions}]-{method_name}-{mapping_id}`
* TestBench.RetryTestResource has a …

test: add support to ITRetryConformanceTest suite to allow running gRPC transport tests

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteSessionConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteSessionConfigs.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BufferToDiskThenUpload.java
google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultBlobWriteSessionConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JournalingBlobWriteSessionConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadBlobWriteSessionConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageInternal.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BufferToDiskThenUploadTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobWriteSessionTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITParallelCompositeUploadBlobWriteSessionConfigTest.java

1. Add TransportCompatibility annotations to factory methods in BlobWriteSessionConfigs
2. Add BlobWriteSessionConfig.GrpcCompatible marker interface for validation in GrpcStorageOptions
3. Add BlobWriteSessionConfig.GrpcCompatible to all existing BlobWriteSessionConfigs
4. Cleanup todo in DefaultBlobWriteSessionConfig that was reaching down into the GrpcBlobWriteChannel. Now, the WritableByteChannelSession will be constructed directly.
5. Add @CrossRun annotations to BlobWriteSession integration tests

chore: blob write session cleanup

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BaseStorageWriteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGrpcStorageImplUploadRetryTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/ITRetryConformanceTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMapping.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/TestRetryConformance.java

Additional small changes to bring http and grpc implementation into conformance with each other.
Much of this also serves as prework to the grpc retry conformance tests enablement after the next release of testbench.

fix: update implementation of readAllBytes and downloadTo to be more robust to retryable errors

---

google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java

[This PR](https://github.com/googleapis/java-storage/commit/4c2f44e28a1ff19ffb2a02e3cefc062a1dd98fdc) introduced a bug in using createFrom to upload a zero byte object. I can't figure out where exactly the bug is, but something is causing the content range to be 0-1 instead of 0-0 in this case. It ends up getting rejected because the range is bigger than the content size, which is still zero.
We can fix the bug later when we identify the root cause, but for now I'm just reverting to the old way of doing it when we detect that we're uploading a zero byte file.
I also added a test for this case

fix: Add an exception to zero byte uploads on CreateFrom

---

.github/.OwlBot.yaml

Preparing owlbot configuration for /google/storage/control/v2. Internal reference: cl/595461040.

chore: owlbot configuration for /google/storage/control/v2

---

.github/.OwlBot.yaml

Owlbot PRs will be removing this IT. This PR prevents it. I found out about this by testing [new GAPIC generation in sdk-platform-java](https://github.com/googleapis/sdk-platform-java/tree/main/library_generation) (I generated a post-processed library and the diff between my generation and the `java-storage` repo was this one missing file)
OwlBot CLI's `copy-code` output (from a local generation):
```
...
rm  /repo/google-cloud-storage-control/src/main/java/com/google/storage/control/v2/StorageControlClient.java
rm  /repo/google-cloud-storage-control/src/main/java/com/google/storage/control/v2/StorageControlSettings.java
rm  /repo/google-cloud-storage-control/src/main/java/com/google/storage/control/v2/stub/GrpcStorageControlCallableFactory.java
rm …
```

chore: deep-preserve for `ITFoldersTest`

---

README.md
google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadBlobWriteSessionConfig.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ParallelCompositeUploadBlobWriteSessionConfigTest.java

This feature enabled the user to create a prefix that will be unique per parallel composite upload. If the user specifies a prefix the prefix will be appended to the ultimate object name which will be appended to the part name to create a staging area for objects per PCU.
If the user does not specify a prefix then the parts will simply be created at the level of the ultimate object name.

feat: Add ability to create a PCU Prefix at the object level

---

README.md
google-cloud-storage/pom.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/HttpStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java

This PR adds an intercept when `UniverseDomain` is set in `StorageOptions`, which overrides the host in StorageOptions. It also changes signed URLs to respect custom hosts, including a specified universe domain. 
There are no tests for this because Kokoro is not able to access any TPC universes yet. I tested all these changes locally, and they're working against the staging universe.

feat: Adds TPC support

---

README.md
storage-shared-benchmarking/src/main/java/com/google/cloud/storage/benchmarking/StorageSharedBenchmarkingCli.java
storage-shared-benchmarking/src/main/java/com/google/cloud/storage/benchmarking/W1R3.java

1. Addressed some late comments on the previous warmup PR. (ie moving warmup outside of samples loop)
2. Added in exits for when we encounter an exception that causes the workload to fail.
3. Fixed metric publishing for failures(-1 to 0), just publish the metric instead of completely failing out of the workload.

chore(benchmarks): Warmup v2

---

.github/sync-repo-settings.yaml
.github/workflows/unmanaged_dependency_check.yaml

This check avoids accidentally adding 3rd party dependencies. This is one of the items listed in go/cloud-sdk-java-dependency-governance-design. Sydney has reviewed this.
b/320677880
---

ci: unmanaged dependency check

---

README.md
storage-shared-benchmarking/src/main/java/com/google/cloud/storage/benchmarking/Bidi.java
storage-shared-benchmarking/src/main/java/com/google/cloud/storage/benchmarking/CloudMonitoringResult.java
storage-shared-benchmarking/src/main/java/com/google/cloud/storage/benchmarking/StorageSharedBenchmarkingCli.java
storage-shared-benchmarking/src/main/java/com/google/cloud/storage/benchmarking/StorageSharedBenchmarkingUtils.java
storage-shared-benchmarking/src/main/java/com/google/cloud/storage/benchmarking/W1R3.java

In order to better compare performance of gRPC and JSON I have removed retries to keep retried requests from impacting latency metrics. We can monitor failed metrics and perhaps in the future publish metrics around if a request would have been retried or not.
I also believe publishing latency is more useful than throughput. If we want throughput the math is simpler to conduct in the dashboards than the other way around.

chore(benchmarking): Remove retries and switch to publishing api_latency instead of throughput

---

google-cloud-storage/pom.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/package-info.java
samples/snippets/src/main/java/com/example/storage/QuickstartGrpcDpSample.java

Update google-cloud-storage package-info to include information on gRPC API in java-storage per product team request.
Borrowed some from: https://github.com/googleapis/google-cloud-cpp/pull/13688

chore: update package-info with gRPC GA Allowlist

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/HttpStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Notification.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java

In files: HttpStorageOptions.java, GrpcStorageOptions.java, Notification.java, StorageOptions.java and UnifiedOpts.java there are some classes that are serializable but it does not contain any serialVersionUID field. The compiler generates one by default in such scenarios, but the generated id is dependent on compiler implementation and may cause unwanted problems during deserialization. 
The primary role of serialVersionUID is to provide version control during deserialization. When deserialize an object, the JVM checks whether the serialVersionUID of the serialized data matches the serialVersionUID of the class in the current classpath. If they match, the deserialization proceeds without issues. However, if they do not match, programmers encounter InvalidClassException.
As, …

fix: missing serialVersionUID of serializable classes

---

.github/workflows/unmanaged_dependency_check.yaml
README.md
renovate.json

In this PR:
- Change renovate config to update java shared config with unmanaged dependency check together.

chore: update renovate config for unmanaged dependency check

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BidiBlobWriteSessionConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultBlobWriteSessionConfig.java

Refactor, reuse DecoratedWritableByteChannelSession and LazySession from DefaultBlobWriteSessionConfig rather than duplicating in BidiBlobWriteSessionConfig.

fix: update BidiBlobWriteSessionConfig to respect a provided bufferSize

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteSessionConfigs.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BufferToDiskThenUpload.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobWriteSessionTest.java

feat: port BufferToDiskThenUpload to work with HttpStorageOptions

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteSessionConfigs.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadBlobWriteSessionConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/RewindableContentInputStream.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/RewindableContentInputStreamTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITParallelCompositeUploadBlobWriteSessionConfigTest.java

feat: port ParallelCompositeUploadBlobWriteSessionConfig to work with HttpStorageOptions

---

.readme-partials.yaml
README.md

We will need to add in additional reference once the quickstart is finished.

docs: Add summary and reference docs for Storage Control API to readme

---

samples/install-without-bom/pom.xml
samples/native-image-sample/pom.xml
samples/snapshot/pom.xml
samples/snippets/pom.xml
samples/snippets/src/main/java/com/example/storage/QuickstartStorageControlSample.java
samples/snippets/src/test/java/com/example/storage/QuickstartSampleIT.java

samples: Add StorageControl Quickstart Sample

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryUnbufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSessionFailureScenario.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSessionPutTask.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITJsonResumableSessionPutTaskTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITJsonResumableSessionTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITUnbufferedResumableUploadTest.java

Despite GCS only allowing incremental updates to a resumable session at 256KiB byte boundaries, we have observed an extremely rare case (<0.000001%) of an incremental write being non-quantum aligned. The change in this PR makes ApiaryUnbufferedWritableByteChannel graceful to this possibility, and will only set the finalization header when close is invoked.
If a write is not quantum aligned, it will either: 1) not be consumed at all, at which point write can be called again with the still enqueued bytes 2) partially consumed, with the position of the provided ByteBuffers updated to reflect how much of their bytes were consumed, matching up with the number of bytes actually consumed returned from `write()`
Add new integration test to intentionally perform non-quantum aligned `write()` calls …

fix: update ApiaryUnbufferedWritableByteChannel to be graceful of non-quantum aligned write calls

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteSession.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteSessions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultBlobWriteSessionConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUploadSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSessionPutTask.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageOptions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobWriteSessionCommonSemanticsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobWriteSessionTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITJournalingBlobWriteSessionConfigTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITParallelCompositeUploadBlobWriteSessionConfigTest.java

* Improve error handling to cover more cases where errors should be converted to StorageException
* Enforce BlobWriteSession#open only being able to be called once, subsequent calls will error
* Make JsonResumableSessionPutTask more graceful when attempting to determine object size (testbench can omit `.size` from its response when the value is 0, possibly due to protobuf to json conversion where protobuf won't explicitly include a 0 value.)
* Update com.google.cloud.storage.StorageException#coalesce to look for ApiException in causes the same way it does for BaseServiceException
* Add com.google.cloud.storage.StorageOptions.Builder#setBlobWriteSessionConfig now that both Http and Grpc support these, having it on the base class is convenient
* Add new integration test …

fix: ensure all BlobWriteSession types conform to the semantics specified in BlobWriteSession

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DefaultQos.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ParallelCompositeUploadCallable.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/Qos.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManager.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITTransferManagerTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/transfermanager/TransferManagerConfigTestingInstances.java

This implements ParallelCompositeUploads(PCU) in Transfer Manager.
ParallelCompositeUpload in Transfer Manager is an opt-in feature, customers will have to update their config to allow Transfer Manager to perform PCU operations on their behalf. Transfer Manager will only do this if the following conditions are met: 
- The customer has set allowParallelCompositeUpload to true
- The file to be uploaded is 4 * the buffer per worker size
- The customer has specified enough threads that ParallelCompositeUpload can be of benefit while still cuing other work.

feat: Transfer Manager ParallelCompositeUploads

---

samples/snippets/src/main/java/com/example/storage/transfermanager/DownloadBucket.java
samples/snippets/src/main/java/com/example/storage/transfermanager/DownloadMany.java
samples/snippets/src/main/java/com/example/storage/transfermanager/UploadDirectory.java
samples/snippets/src/main/java/com/example/storage/transfermanager/UploadMany.java
samples/snippets/src/test/java/com/example/storage/transfermanager/ITTransferManagerSamples.java

Samples for the upload many operations only. Will do chunked once Parallel Composite Upload is complete.

docs: Create Samples for transfer manager

---

.repo-metadata.json
README.md

Adds a field for recommended_package as part of the revamped Library Overviews.
See go/cloud-rad-overviews-handwritten-repos for more details

chore: include recommended_package in repo-metadata.json

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcRetryAlgorithmManager.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/CtxFunctions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/ITRetryConformanceTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java

Etags returned by the JSON api are base64 encoded, and IAM Policy is currently modeled around this for its public api. Update GrpcConversions to base64 decode/encode appropriately.

fix: update grpc handling of IAM Policy etag to account for base64 encoding

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GzipReadableByteChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITReadChannelGzipHandlingTest.java

If the ReadChannel chunkSize is 0 there will be no library buffering performed during read calls. If gzip decompression support is enabled on the read channel, there is a possibility someone could read fewer than the 4 bytes we initially read.
This change updates the byte tracking to ensure single byte reads are supported.

fix: update GzipReadableByteChannel to be tolerant of one byte reads

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadJob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadResult.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ParallelDownloadConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ParallelUploadConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManager.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferStatus.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadJob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadResult.java

feat: Remove @BetaApi Annotations for Transfer Manager operations

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedChunkedResumableWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicWritableByteChannelSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSessionPutTask.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSessionQueryTask.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ResumableSessionFailureScenario.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ResumableWrite.java
google-cloud-storage/src/main/java/com/google/cloud/storage/RewindableContent.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGapicUnbufferedChunkedResumableWritableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGapicUnbufferedWritableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ResumableSessionFailureScenarioTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/TestUtils.java

* Rename JsonResumableSessionFailureScenario to ResumableSessionFailureScenario. The failure scenarios themselves are not json specific, and the methods which are json specific can have grpc overloads
* Add more tests to validate GapicUnbufferedChunkedResumableWritableByteChannel is able to properly detect and handle various success responses from GCS which are not success for the client.

fix: add strict client side response validation for gRPC chunked resumable uploads

---

google-cloud-storage/src/main/java/com/google/cloud/storage/AsyncStorageTaskException.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedChunkedResumableWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ResumableSessionFailureScenario.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ResumableSessionFailureScenarioTest.java

Follow up to #2527 
This updated errors from grpc chunked uploads to have messages that include useful debugging information.
When a response is received but doesn't validate with the expected state: 
```
com.google.cloud.storage.StorageException: Attempt to append to already finalized resumable session.
|> [
|> 	com.google.storage.v2.WriteObjectRequest{
|> 		upload_id: uploadId
|> 		checksummed_data: {range: [0:262144]}
|> 	}
|> ]
|  
|< com.google.storage.v2.WriteObjectResponse{
|< 	resource {
|< 	  name: "obj"
|< 	  size: 524288
|< 	}
|< }
|
```
When an error is returned by GCS:
```
com.google.cloud.storage.StorageException: Client side data loss detected. Attempt to append to a resumable session with an offset higher than the backend has
|> [
|> …
```

fix: update grpc WriteObject response handling to provide context when a failure happens

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/GrpcPlainRequestLoggingInterceptor.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/BackendResources.java

Grpc's built-in logging is very robust, but does not print request/response messages in "plain text", instead logging byte codes sequences. This interceptor instead logs the protobuf messages in their normal plain text rendering. By default, the logging is disabled. The category needs to be set to CONFIG or higher to see the logs.

test: add GrpcPlainRequestLoggingInterceptor and add it to BackendResources

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITTransferManagerTest.java

feat: Plumb PartNamingStrategy for Parallel Composite Uploads in Transfer Manager

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ChunkSegmenter.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedChunkedResumableWritableByteChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ChunkSegmenterTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITUnbufferedResumableUploadTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/PackagePrivateMethodWorkarounds.java

Update GapicUnbufferedChunkedResumableWritableByteChannel to only accept bytes at the 256KiB boundary when `write(ByteBuffer[], int, int)` is called.
Calls to `writeAndClose(ByteBuffer[], int, int)` will consume all bytes.

fix: update GapicUnbufferedChunkedResumableWritableByteChannel to be tolerant of non-quantum aligned writes

---

google-cloud-storage/src/main/java/com/google/cloud/storage/AsyncAppendingQueue.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BaseStorageReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BaseStorageWriteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobReadChannelV2.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannelV2.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadBlobWriteSessionConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageByteChannels.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ThroughputSink.java

Setup a small workload using virtual threads and turned on pinning detection (`-Djdk.tracePinnedThreads=full`), and run various methods for uploading and downloading object data.
I then reduced the pinning sights to a minimized list (`grep 'monitor' run.log | grep 'com.google.cloud.storage' | sort -u`)
```
com.google.cloud.storage.BaseStorageReadChannel.read(BaseStorageReadChannel.java:105) <== monitors:1
com.google.cloud.storage.BlobWriteSessions$WritableByteChannelSessionAdapter.open(BlobWriteSessions.java:46) <== monitors:1
com.google.cloud.storage.LazyWriteChannel.getSession(LazyWriteChannel.java:59) <== monitors:1
com.google.cloud.storage.ParallelCompositeUploadWritableByteChannel.close(ParallelCompositeUploadWritableByteChannel.java:268) <== monitors:1 …
```

fix: reduce Java 21 Virtual Thread Pinning in IO operations

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java

Based on feedback from https://github.com/googleapis/java-storage/issues/2509

docs: update javadoc for createFrom

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedDirectWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicWritableByteChannelSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ResumableSessionFailureScenario.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGapicUnbufferedDirectWritableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGapicUnbufferedWritableByteChannelTest.java

Follow up to #2527
This updated errors from grpc single-shot uploads to have messages that include useful debugging information.
When a response is received but doesn't validate with the expected state:
```
com.google.cloud.storage.StorageException: Finalized upload, but object size less than expected.
|> [
|> 	com.google.storage.v2.WriteObjectRequest{
|> 		write_offset: 524288
|> 		finish_write: true
|> 	}
|> ]
|
|< com.google.storage.v2.WriteObjectResponse{
|< 	resource {
|< 	  name: "obj"
|< 	  size: 262144
|< 	}
|< }
|
```

fix: update grpc single-shot uploads to validate ack'd object size

---

samples/snippets/src/main/java/com/example/storage/control/v2/CreateFolder.java
samples/snippets/src/main/java/com/example/storage/control/v2/CreateHierarchicalNamespaceBucket.java
samples/snippets/src/main/java/com/example/storage/control/v2/DeleteFolder.java
samples/snippets/src/main/java/com/example/storage/control/v2/GetFolder.java
samples/snippets/src/main/java/com/example/storage/control/v2/ListFolders.java
samples/snippets/src/main/java/com/example/storage/control/v2/RenameFolder.java
samples/snippets/src/test/java/com/example/storage/control/v2/FoldersTest.java
samples/snippets/src/test/java/com/example/storage/control/v2/HNSTest.java

New samples
* `storage_create_bucket_hierarchical_namespace`
* `storage_control_create_folder`
* `storage_control_delete_folder`
* `storage_control_get_folder`
* `storage_control_list_folders`
* `storage_control_rename_folder`
Fixes #2569

docs: add Hierarchical Namespace Bucket and Folders samples

---

google-cloud-storage/src/main/java/com/google/cloud/storage/testing/RemoteStorageHelper.java
samples/snippets/src/test/java/com/example/storage/ITStorageSnippets.java

chore: Fix broken sample tests

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedFinalizeOnCloseResumableWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicWritableByteChannelSessionBuilder.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGapicUnbufferedFinalizeOnCloseResumableWritableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/TestUtils.java

Follow up to #2527 and #2514
* Add ITGapicUnbufferedFinalizeOnCloseResumableWritableByteChannelTest with failure scenarios
* Refactoring to clean up some request building lifecycle and variable scope
* Update GapicUnbufferedFinalizeOnCloseResumableWritableByteChannel to validate ack'd object size

fix: update grpc finalize on close resumable uploads to validate ack'd object size

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BidiResumableWrite.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BidiWriteCtx.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicBidiUnbufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicBidiWritableByteChannelSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ResumableSessionFailureScenario.java
google-cloud-storage/src/test/java/com/google/cloud/storage/FakeServer.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGapicBidiUnbufferedWritableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/GrpcPlainRequestLoggingInterceptor.java

Follow up to #2527 and #2514
The tests added in this PR account for ~940 of the added lines, however their scenarios are the same as the other upload scenario tests just using the different proto types. The remaining ~300 lines are the fix and small refactor to get the tests passing. I've left individual commits in the PR to make it easier to drill down if needed.
* Part 1, add tests and simulation server
* Tests are a port of those added in #2527 using BidiWriteObjectRequest and BidiWriteObjectResponse
* simulation server is a port of com.google.cloud.storage.ITGapicUnbufferedWritableByteChannelTest.DirectWriteService using BidiWriteObjectRequest and BidiWriteObjectResponse
* Cleanup unused inner-class
* Move request trimming inline rather than at the end
* Update …

fix: update grpc bidi resumable uploads to validate ack'd object size

---

README.md
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageOptionsBuilderTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITGrpcTest.java

Workaround in place until https://github.com/googleapis/sdk-platform-java/issues/2911 is fixed

fix: add a workaround to make sure grpc clients' hosts always match their universe domain

---

.github/sync-repo-settings.yaml

Follow up to https://github.com/googleapis/java-storage/pull/2566 that disabled owlbot in favor of hermetic generator

chore: remove OwlBot required status check from sync-repo-settings.yaml

---

renovate.json

Renovate will open individual PRs for mutli-module projects where we depend on multiple artifacts. In an effort to make reviews of these PRs simpler, and to reduce CI compute time group them together.

chore: update renovate config to apply grouping to recently added dependencies

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedFinalizeOnCloseResumableWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ResumableSessionFailureScenario.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Utils.java

When a client is shutting down, the Channel pool will deliver an error to our stream observer. This could happen before we are able to actually write a message. Update GapicUnbufferedFinalizeOnCloseResumableWritableByteChannel to not attempt to pass null to ImmutableList.of().
Sample exception
```
java.lang.NullPointerException
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:906)
at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:41)
at com.google.common.collect.ImmutableList.of(ImmutableList.java:101)
at com.google.cloud.storage.GapicUnbufferedFinalizeOnCloseResumableWritableByteChannel$Observer.onError(GapicUnbufferedFinalizeOnCloseResumableWritableByteChannel.java:233)
at …
```

fix: update grpc resumable upload error categorization to be more tolerant

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITGrpcTest.java
samples/snippets/src/test/java/com/example/storage/QuickstartSampleIT.java

Closing instance of storage that gets abandoned and then eventually cleaned up which results in a long error message that pollutes the logs
Fixes issue #2612

test: Turn DirectPath quickstart test back on and fix abandoned storage instance in GRPC test

---

.github/sync-repo-settings.yaml

Can be re-enabled once https://github.com/googleapis/sdk-platform-java/pull/3078 is merged and released

chore: temporarily disabled the required status on unmanaged_dependency_check

---

.repo-metadata.json
README.md
generation_config.yaml

Solves https://github.com/googleapis/java-storage/pull/2631#discussion_r1681551588

chore: modify readme's transport support description

---

samples/install-without-bom/pom.xml
samples/snippets/pom.xml

* Close `dependencies` element for `storage_install_with_bom`
* Remove release please comment for storage control from `storage_install_without_bom`. Instead, allow renovate-bot to update when the version is available in maven central.
* remove duplicate declaration of `google-cloud-storage-control` in install-without-bom/pom.xml

chore: fix samples pom.xml issues

---

google-cloud-storage/src/main/java/com/google/cloud/storage/JsonConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Utils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITJsonPatchTest.java

Update StorageImpl#update(BlobInfo) and StorageImpl#update(BucketInfo) to only send modified fields in the case of an actual update. Currently, it simply sends the json version of the current info, this can mean that if a field is cleared the request to gcs doesn't actually include the field to clear.
This same issue does not impact grpc transport, because grpc transport has an explicit `update_mask` that is populated.
Add some tests to ensure things work and continue to work.
In order to handle this, we have to explicitly include a `Data.nullOf(Class)` in the respective apiary model. Each of the `Data.nullOf`s must match the type of the field. Because of this, we now need to track the apiary type for each field. To this end, a new internal field has been added to BlobField and …

fix: update modified field handling for blob and bucket with json transport to properly clear fields

---

google-cloud-storage/src/test/java/com/google/cloud/storage/FakeServer.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITStorageLifecycleTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RetryTestFixture.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITGrpcIdempotencyTokenTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageOptionsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/BackendResources.java

Our test suite creates thousands of instances of storage clients, the vast majority against test bench and non-directpath. Explicitly disable grpc client metrics to avoid the bootstrapping overhead and permission failures that happen.

test: disable grpc client side metrics for tests

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BidiBlobWriteSessionConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultBlobWriteSessionConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicBidiUnbufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedChunkedResumableWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUploadSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JournalingBlobWriteSessionConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSessionPutTask.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GapicUploadSessionBuilderSyntaxTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITSyncAndUploadUnbufferedWritableByteChannelPropertyTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITUnbufferedResumableUploadTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITResumableUploadTest.java

Update resumable upload failure detection to be more specific about classifying a request as SCENARIO_5
Fixes #2511

feat: allow specifying an expected object size for resumable operations.

---

google-cloud-storage/pom.xml
pom.xml

Junit 5 sometimes can fail to locate tests, due to a version mismatch between junit cross module dependencies. To avoid this, update our maven config to use the [Junit 5 BOM](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven-bom).
Example exception:
```
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:132)
at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:107)
at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.disc …
```

build: switch to using junit 5 bom

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ResponseContentLifecycleManager.java

Update gRPC based Storage instances to close out in progress reads when zero-copy is used and Storage#close() is called.

fix: close pending zero-copy responses when Storage#close is called

---

.github/workflows/hermetic_library_generation.yaml

Hi! I'm Diogo from Google's Open Source Security Team([GOSST](https://opensource.googleblog.com/2023/04/googles-open-source-security-upstream-team-one-year-later.html)) and I'm dropping by to suggest this small change that will enhance the security of your repository by preventing script injection attacks through your GitHub workflows.
In the piece of code I changed, you were directly using the value of a variable that comes from a user's input, so a malicious user could exploit that input and use it to run arbitrary code. By using an intermediate environment variable, the value of the expression is stored in memory, used as a variable and doesn't interact with the script generation process. This mitigates the script injection risks and also keeps your workflow running exactly as before. …

fix: github workflow vulnerable to script injection

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicDownloadSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcBlobReadChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGapicUnbufferedReadableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGzipReadableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/TestUtils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageReadChannelTest.java

Update GapicUnbufferedReadableByteChannel to manage the grpc stream itself rather than using the stream iterator provided by gax. This allows us to ensure the cancellation is observed and our draining performs before returning from close().
As a side effect of not using the gax stream iterator, we now must handle stream restarts ourselves. GrpcStorageOptions.ReadObjectResumptionStrategy has been removed entirely, while RetryingDependencies and ResultRetryAlgorithm are now plumbed all the way down to the GapicUnbufferedReadableByteChannel.

fix: update grpc based ReadObject rpcs to remove race condition between cancellation and message handling

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITServiceAccountTest.java

Partial revert of 96b6330297a7206da199ed13905beb10883efb59

fix: remove server unimplemented GrpcStorageImpl#getServiceAccount

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/StorageNativeCanary.java
google-cloud-storage/src/test/resources/META-INF/native-image/com/google/cloud/storage/reflect-config.json
google-cloud-storage/src/test/resources/META-INF/native-image/com/google/cloud/storage/resource-config.json

Add reflect-config for each of grpc's protobuf messages, builders and enums.
See https://github.com/googleapis/java-storage/issues/2716#issuecomment-2374899273 for a code snippet of how this was generated
Fixes #2716

test: update reflect-config for StorageNativeCanary to allow directpath to work

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGapicUnbufferedReadableByteChannelTest.java

If a read is opened without a generation, we want to ensure we restart for the same generation. We have this behavior for [json](https://github.com/googleapis/java-storage/blob/3bce87a0742eb8fc715a6610fbe4e7a0394e501c/google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryUnbufferedReadableByteChannel.java#L234-L238)
This is mainly to avoid a race condition of reading an object (gen=1), that object being replaced (gen=2) then retry attempts to read it again we need to read gen=1 otherwise we will return corrupted data.

chore: ensure generation is included when a grpc ReadObject is retried

---

.readme-partials.yaml
README.md

The versions in REAME are now managed by hermetic build generation scripts, release-please configuration should be remove from README to prevent double-edit.
In addition, release-please configurations were [misconfigured for libraries-bom](https://github.com/googleapis/java-storage/blame/003d6faaa3d64310cf91a1e304247e2f44a5c9c7/README.md#L63),  we have been incorrectly using the storage version for libraries-bom in README.

chore: Remove release-please configs from README.

---

.github/workflows/hermetic_library_generation.yaml

Any changes to the hermetic build inputs should trigger re-regeneration, hence add all of them to `paths` in `hermetic_library_generation.yaml`. This is to resolve an issue found yesterday that hermetic code generation was not triggered in this PR https://github.com/googleapis/java-storage/pull/2755.
We don't have `paths` configured for any other handwritten libraries. IIRC, it was added for a special use case in Storage, @BenWhitehead can you please verify the changes in this PR does not affect other use cases?

chore: Any changes to the hermetic build inputs should trigger re-regeneration

---

google-cloud-storage/src/main/java/com/google/cloud/storage/JournalingBlobWriteSessionConfig.java

Now properly reports grpc only rather than incorrect http only.
This line actually executing was guarded upstream of its construction, but this is being cleaned up for the sake of completeness.

chore: fix error message for JournalingBlobWriteSessionConfig

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java

Prevent adding an unavailable error to the queue if the retrying loop is still active.
Also, cleanup unused retry config for gRPC ReadObject.

fix: update gRPC ReadObject retry to avoid double retry

---

gapic-google-cloud-storage-v2/pom.xml
google-cloud-storage-bom/pom.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/HttpStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageOptions.java
grpc-google-cloud-storage-v2/pom.xml
pom.xml
proto-google-cloud-storage-v2/pom.xml
versions.txt

Remove beta annotations from artifact versions and class/methods on the public api.

feat: promote gRPC transport to GA

---

.github/sync-repo-settings.yaml
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/otel/OpenTelemetryInstance.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITOpenTelemetryTest.java

To keep this more closely aligned with the introduction in HTTP the scope here is small.
To follow will be to add the attributes for recording exceptions and testing that flow.

feat: Add OpenTelemetry Traces to GRPC

---

google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITHttpOpenTelemetryTest.java

feat: Add CreateBlob for HTTP

---

google-cloud-storage/src/main/java/com/google/cloud/storage/OpenTelemetryBootstrappingUtils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGrpcMetricsTest.java

fix: set default values for monitored resource

---

google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITHttpOpenTelemetryTest.java

feat: Instrument HTTP Reads and Rewrites

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/otel/NoOpOpenTelemetryInstance.java
google-cloud-storage/src/main/java/com/google/cloud/storage/otel/OpenTelemetryInstance.java
google-cloud-storage/src/main/java/com/google/cloud/storage/otel/OpenTelemetryTraceUtil.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITHttpOpenTelemetryTest.java

`SpanData{spanContext=ImmutableSpanContext{traceId=c49154a1f7a6a4adb7188e566fcd7d12, spanId=7dd45a835177a216, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, resource=Resource{schemaUrl=null, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.42.1"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=cloud.google.com/java/storage, version=, schemaUrl=null, attributes={}}, name=com.google.cloud.storage.GrpcStorageImpl/create, kind=CLIENT, …

feat: Take in a module name when creating a span

---

google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITHttpOpenTelemetryTest.java

feat: Instrument HTTP readAllBytes

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGrpcOpenTelemetryTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/TestBench.java

feat: Instrument gRPC downloadTo and Copy

---

google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITHttpOpenTelemetryTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/TestBench.java

feat: Instrument HTTP createFrom

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/testing/RemoteStorageHelper.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGapicReadTimeoutTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobWriteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITHmacTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/TestBench.java
google-cloud-storage/src/test/java/com/google/cloud/storage/testing/RemoteStorageHelperTest.java

This PR introduces `java.time` alternatives to existing `org.threeten.bp.*` methods, as well as switching internal variables (if any) to `java.time`
The main constraint is to keep the changes backwards compatible, so for each existing threeten method "`method1(org.threeten.bp.Duration)`" we will add an alternative with a _Duration_ (or _Timestamp_ when applicable) suffix: "`method1Duration(java.time.Duration)`".
For most cases, the implementation will be held in the `java.time` method and the old threeten method will just delegate the call to it. However, for the case of abstract classes, the implementation will be kept in the threeten method to avoid breaking changes (i.e. users that already overloaded the method in their user code).

feat: introduce `java.time` methods and variables

---

samples/snippets/src/main/java/com/example/storage/ConfigureRetries.java
samples/snippets/src/main/java/com/example/storage/bucket/DisableRequesterPays.java
samples/snippets/src/main/java/com/example/storage/bucket/DisableSoftDelete.java
samples/snippets/src/main/java/com/example/storage/bucket/EnableLifecycleManagement.java
samples/snippets/src/main/java/com/example/storage/bucket/EnableUniformBucketLevelAccess.java
samples/snippets/src/main/java/com/example/storage/bucket/GetSoftDeletePolicy.java
samples/snippets/src/main/java/com/example/storage/bucket/MakeBucketPublic.java
samples/snippets/src/main/java/com/example/storage/bucket/SetBucketAutoclass.java
samples/snippets/src/main/java/com/example/storage/bucket/SetPublicAccessPreventionEnforced.java
samples/snippets/src/main/java/com/example/storage/bucket/SetPublicAccessPreventionInherited.java
samples/snippets/src/main/java/com/example/storage/bucket/SetRetentionPolicy.java
samples/snippets/src/main/java/com/example/storage/bucket/SetSoftDeletePolicy.java
samples/snippets/src/main/java/com/example/storage/object/ListSoftDeletedObjects.java
samples/snippets/src/main/java/com/example/storage/object/ListSoftDeletedVersionsOfObject.java
samples/snippets/src/main/java/com/example/storage/object/RestoreSoftDeletedObject.java
samples/snippets/src/test/java/com/example/storage/ITBucketSnippets.java
samples/snippets/src/test/java/com/example/storage/ITObjectSnippets.java
samples/snippets/src/test/java/com/example/storage/QuickstartSampleIT.java

Samples for working with soft deleted objects, intended for https://cloud.google.com/storage/docs/use-soft-delete and https://cloud.google.com/storage/docs/use-soft-deleted-objects

docs: add samples for soft delete (objects)

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGrpcOpenTelemetryTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITHttpOpenTelemetryTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITOpenTelemetryTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/TestBench.java

This PR also adds back testbench support that was previously removed for local development.

feat: Instrument Reader and Writer methods

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryUnbufferedReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java

If the initial response failed with a retryable error and the error should be retried, it wasn't. It would only retry for reading bytes after the initial response had been received.

fix: update retry lifecycle when attempting to decompress a gzip object

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java

If our thread is interrupted while attempting to drainQueue poll will throw an InterruptedException, instead of setting the flag back on the thread immediately we need to defer setting it until we complete our draining. If we don't defer setting it, we can never actually drain our queue.
Manually tested repro and fix with the following code sample, which mirrors the pattern in `drainQueue`.
```
import java.io.IOException;
import java.io.InterruptedIOException;
import java.util.concurrent.ArrayBlockingQueue;
final class InterruptSpiral {
public static void main(String[] args) {
final ArrayBlockingQueue<String> queue = new ArrayBlockingQueue<>(2);
Thread main = Thread.currentThread();
Thread thread = new Thread(() -> {
try {
queue.add("String 1");
main.interrupt();
Thread.sleep(2500); …
```

fix: fix interrupt spiral in grpc ReadObject drainQueue

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/annotations/BucketType.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/BackendResources.java

Reduced wall time from ~2m to ~50 seconds
Add a versioned bucket type available for injection with `@BucketFixture(VERSIONED)` rather than needing to create multiple times per test.

test: update ITObjectTest to be parallel friendly

---

google-cloud-storage/pom.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/OtelStorageDecorator.java
google-cloud-storage/src/test/java/com/google/cloud/storage/PackagePrivateMethodWorkarounds.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/BackendResources.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/ObjectsFixture.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/OtelSdkShim.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/Registry.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/TestRunScopedInstance.java

Integrate OpenTelemetry tracing into our StorageITRunner.
By default the `OpenTelementry.noop()` instance will be used (avoiding the need for the requisite permissions).
To enable trace exporting for the tests, and the storage instances provide either the system property `STORAGE_IT_OTEL_ENABLE=true` or the environment variable `STORAGE_IT_OTEL_ENABLE=true`. They are evaluated as an `OR`, meaning that if both are specified and one is true and one is false, tracing will be enabled.
An example screenshot showing the registry cleaning up after test runs:

test: integrate otel into our StorageITRunner

---

google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITSignedUrlTest.java

fix: update Signed URL default scheme to resolve from storage options host

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITUniverseDomainTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/BackendResources.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/Registry.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/TestRunScopedInstance.java

test: make registry fixture names more "name~spacy" to appear better in otel traces

---

.github/release-please.yml
.github/sync-repo-settings.yaml

this is to create a long running branch for LTS 8 as well as ensure we bump the minor version

feat: next release from main branch is 2.48.0

---

google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageExceptionGrpcCompatibilityTest.java

Update StorageException logic for coalescing ApiExceptions to add a formatted string including fields from error details as a suppressed exception on the api exception.
This keeps the diagnostic information at the "gapic layer" in the printed stacktrace similar to the json document being on the "apiary layer" of the cause.
The change here will produce something like the following:
```
com.google.cloud.storage.StorageException: OUT_OF_RANGE
at com.google.cloud.storage.StorageException.asStorageException(StorageException.java:165)
at com.google.cloud.storage.StorageException.coalesce(StorageException.java:123)
at com.google.cloud.storage.StorageExceptionGrpcCompatibilityTest.apiExceptionErrorDetails(StorageExceptionGrpcCompatibilityTest.java:191)
at …
```

fix: update StorageException translation of an ApiException to include error details

---

google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSession.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBatchTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITHttpIdempotencyTokenTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/spi/v1/HttpRpcContextTest.java

If batch is used to update an object, and that subrequest has an `x-goog-idempotency-token` set on it, that token can be used to short circuit execution of the request if that token has already been processed (essentially interpreting the request as a retry).
Previously, we didn't set idempotency token for batch operations, but the IdempotencyIdInterceptor would still attach one if it was visible in the thread local.
Update our handling, so that we alway set a new unique token for each batch operation making it immune to any possibly still visible thread local value.
HTTP Request logs of what this will now look like.
```
2025-01-30 14:20:38,489 CONFIG   com.google.api.client.http.HttpTransport           - -------------- REQUEST  --------------
POST …
```

fix: update batch handling to ensure each operation has its own unique idempotency-token

---

samples/snippets/src/main/java/com/example/storage/object/CopyObject.java
samples/snippets/src/test/java/com/example/storage/ITObjectSnippets.java

The GCS API that underpins `Storage#copy(CopyRequest)` is [`storage.objects.rewrite`](https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite).
A rewrite is technically what we now refer to in Google Cloud API land as a Long Running Operation, meaning it's structured in such a way as to be able to take longer than would normally be acceptable for a single RPC.
In the case of performing the rewrite, GCS is "moving" the bytes over the google network and won't respond to the request at all until complete. If it takes GCS more than the client configured read timeout to actually "move" the bytes, the client interprets it as a read timeout and fails out.
Update the code snippet for copy to make it more robust to large objects.

docs: update storage_copy_file to include MegabytesCopiedPerChunk

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageOptionsTest.java

Project id is only needed as a default for some operations, don't prevent constructing an instance of GrpcStorageImpl if project id is unresolved.

fix: update grpc based Storage to defer project id validation

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java

docs: add note about HNS support to moveBlob

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/BucketNameMismatchException.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ParallelUploadConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerUtils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITTransferManagerTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/transfermanager/TransferManagerTest.java

When uploading a file from the files system, there are scenarios when a job would need to customize the actual BlobInfo used to upload to GCS.
Add the new UploadBlobInfoFactory which allows a user to produce their own BlobInfo instance given the bucketName and fileName. When producing the BlobInfo the application can also customize other metadata fields.
A few convenience adapter methods are available in UploadBlobInfoFactory to simplify common operations.
Fixes #2638

feat(transfer-manager): add ParallelUploadConfig.Builder#setUploadBlobInfoFactory

---

google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java

fix: update kms key handling when opening a resumable upload to clear the value in the json to be null rather than empty string

---

google-cloud-storage/src/test/resources/logback.xml
renovate.json

Update default log levels for http and grpc requests
Follow-up for #2948  and #2946

chore: add renovate logging config

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryUnbufferedReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSession.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSessionPutTask.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSessionQueryTask.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableWrite.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ResumableSessionFailureScenario.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Utils.java
google-cloud-storage/src/main/java/com/google/cloud/storage/XGoogApiClientHeaderProvider.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITExtraHeadersOptionTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITJsonResumableSessionPutTaskTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITJsonResumableSessionQueryTaskTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/UnifiedOptsGrpcTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/AssertRequestHeaders.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/GrpcRequestAuditing.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/RequestAuditing.java

Add new "Option"s for those methods which already have option types to allow providing an ImmutableMap<String, String> to be applied as extra headers to all requests sent as part of that operation.
If an operation has multiple sources of input Options (rewrite) the "first" (i.e. source option) will be the one added to the request.
The following resources do not have "Option"s and therefor do not have extra headers support at this time:
* Acl
* DefaultAcl
* ServiceAccount
* Notification
This blind number of lines is large, but the number of differences is actually fairly low.
* Add `Headers` Opt` in UnifiedOpts, this is the primary guts of the new feature and is responsible for holding onto the extra header values and validating the provided headers to ensure no collisions with headers …

feat: add new Options to allow per method header values

---

google-cloud-storage/src/main/java/com/google/cloud/storage/JsonResumableSessionQueryTask.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITJsonResumableSessionQueryTaskTest.java

Port `NullPointerException` fix of `JsonResumableSessionPutTask` in 9b4bb8221294bcd94037b69281a37f33b364b174 to `JsonResumableSessionQueryTask`, which has similar code.

fix: improve 503 handling for json resumable uploads

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicBidiUnbufferedWritableByteChannel.java

onError can be called before a message is written to the stream, make sure we are accounting for the possibility that lastWrittenRequest can be null.
The fix prevents the following type of NPE from happening
```
Feb 18, 2025 10:39:15 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed@5b549e5c
java.lang.NullPointerException
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:904)
at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:42)
at com.google.common.collect.ImmutableList.of(ImmutableList.java:101)
at com.google.cloud.storage.GapicBidiUnbufferedWritableByteChannel$BidiObserver.onError(GapicBidiUnbufferedWritableByteChannel.jav …
```

fix: update gRPC Bidi resumable upload to have more robust error message generation

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketTest.java

StorageImpl will return null if a bucket is not found, this updates GrpcStorageImpl to do the same.

fix: update gRPC implementation for storage.buckets.get to translate NOT_FOUND to null

---

google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java

If a generation is present in the provided BlobInfo ensure it is sent to GCS. This is a hard requirement when using versioned buckets and trying to update a non-current object version.
Effects all version 2.42.0 through 2.50.0
Regression introduced in #2664
Fixes #2980

fix: ensure object generation is sent for Storage#update(BlobInfo) using HTTP Transport

---

pom.xml

gcp-resources still declares a version for now, but that will also be added to shared-deps and removed later

deps: remove explicit version declarations for packages that are in shared-dependencies 

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryUnbufferedReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadChannelTest.java

If a 416 or OUT_OF_RANGE error are encountered the channel will always return -1, even if a new generation of object is created.

fix: update 416 & OUT_OF_RANGE handling for ReadChannel

---

google-cloud-storage/src/main/java/com/google/cloud/storage/AsyncSessionClosedException.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobReadSession.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ObjectReadSessionImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ObjectReadSessionStream.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ReadAsFutureByteString.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ReadAsFutureBytes.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ReadProjectionConfigs.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ZeroCopySupport.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITObjectReadSessionFakeTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITObjectReadSessionTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ObjectReadSessionStreamTest.java

Additional javadocs, test added to ensure getting a future after a session has closed results in an exception.

chore: make ReadProjectionConfigs#asFuture{Bytes,ByteString} public

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ObjectReadSessionStream.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITObjectReadSessionFakeTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITObjectReadSessionTest.java

When a read causes an error it is delivered as a stream error. Depending on the kind of error (DATA_LOSS OUT_OF_RANGE) this could lead to a terminal state for the stream. If the error is for a specific range(s) mark those individual reads as terminally failed, but do not fail any others. Instead, raise a client side retryable ABORTED to restart the stream and any remaining reads for it.

chore: improve read object range error handling and retry robustness

---

google-cloud-storage/src/test/java/com/google/cloud/storage/ITAppendableUploadTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITObjectReadSessionTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/annotations/BucketType.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/BackendResources.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/BucketInfoShim.java

Update ITAppendableUploadTest and ITObjectReadSessionTest to use the rapid bucket instead of testbench.
Beacuse rapid buckets are not yet available in all zones, if we attempt to make the rapid bucket and it fails the test will be skipped instead of failing.

test: add rapid bucket fixture

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobAppendableUpload.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobAppendableUploadConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobAppendableUploadImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ChannelSession.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicBidiUnbufferedAppendableWriteableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicBidiWritableByteChannelSessionBuilder.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/OtelStorageDecorator.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITAppendableUploadFakeTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITAppendableUploadTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITObjectReadSessionTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/AbstractStorageProxy.java

This allows access to the resulting BlobInfo, even if not finalized. The returned BlobInfo will have generation and a client side updated `size` matching the number of persisted bytes the client knows has been ack'd by GCS.
Add closeAction option to BlobAppendableUploadConfig allowing configuration of finalization on close behavior.

chore: refactor BlobAppendableUpload, so it follows the lifecycle of BlobWriteSession

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ObjectReadSessionSeekableByteChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ObjectReadSessionLifeCycleTest.java

Update SeekableChannel close() to only execute close logic once.

chore: fix BlobReadSession ReadProjectionConfigs.asSeekableChannel() close() behavior

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/OpenTelemetryBootstrappingUtils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGrpcMetricsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/OpenTelemetryBootstrappingUtilsTest.java

Refactor OpenTelemetryBootstrappingUtils to return a channel configurator function rather than mutating a passed in value.
Add ChannelConfigurator interface to make testing easier and to simplify composition with any existing channel configurator function present in the InstantiatingGrpcChannelProvider.

fix: update grpc client side metrics detection to be graceful when not running on gcp

---

google-cloud-storage/src/test/java/com/google/cloud/storage/ITGapicBidiUnbufferedWritableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITGapicUnbufferedWritableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/ITRetryConformanceTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RetryTestFixture.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/BucketCleaner.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/GrpcPlainRequestLoggingInterceptor.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobWriteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITNotificationTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/StorageITLeafRunner.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/TestBench.java

OpenTelemetry brought with it slf4j and we already have logback configured for tests. Update our tests to use slf4j directly instead of java.util.logging.
This avoids the need for the j.u.l messages to be redirected through an slf4j adapter before making it to logback.

test: switch all test logging to slf4j instead of j.u.l

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java

This will have the generation present making the delete idempotent and retryable.

test: update ITObjectTest copy tests to delete blobid instead of blob name

---

google-cloud-storage/src/test/java/com/google/cloud/storage/ITAppendableUploadTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITObjectReadSessionTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/Zone.java
google-cloud-storage/src/test/resources/logback.xml

Persistent 503 errors are happening for RAPID buckets in `us-west1-a`. Exclude running in PROD for the time being, instead running only against testbench.

test: disable rapid bucket tests in PROD

---

samples/snippets/src/main/java/com/example/storage/control/v2/AnywhereCacheCreate.java
samples/snippets/src/main/java/com/example/storage/control/v2/AnywhereCacheDisable.java
samples/snippets/src/main/java/com/example/storage/control/v2/AnywhereCacheGet.java
samples/snippets/src/main/java/com/example/storage/control/v2/AnywhereCacheList.java
samples/snippets/src/main/java/com/example/storage/control/v2/AnywhereCachePause.java
samples/snippets/src/main/java/com/example/storage/control/v2/AnywhereCacheResume.java
samples/snippets/src/main/java/com/example/storage/control/v2/AnywhereCacheUpdate.java
samples/snippets/src/test/java/com/example/storage/control/v2/ITAnywhereCacheTest.java

* storage_control_create_anywhere_cache
* storage_control_disable_anywhere_cache
* storage_control_get_anywhere_cache
* storage_control_list_anywhere_cache
* storage_control_pause_anywhere_cache
* storage_control_resume_anywhere_cache
* storage_control_update_anywhere_cache
Port of https://github.com/googleapis/google-cloud-cpp/pull/15134

samples(storagecontrol): add AnywhereCache samples

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/GrpcPlainRequestLoggingInterceptor.java

Update all `fmtProto` methods to use `fmtProto(MessageOrBuilder)` instead of `Message#toString`

test: update GrpcPlainRequestLoggingInterceptor to also log headers when x-retry-test-id is present

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java

This will allow the gRPC channel provider to set up hard bound (compute engine) call credentials for the channel when DirectPath is compatible.
If the GCE/GKE metadata servers' support for such bound access tokens is not available yet, it will end up getting the normal unbound ones and nothing should fail.
No public storage API is changed.

feat: enable ALTS bound token (for DirectPath) in the grpc channel provider

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/BidiAppendableUnbufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BidiUploadState.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BidiUploadStreamingStream.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobAppendableUpload.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobAppendableUploadImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BufferedWritableByteChannelSession.java
google-cloud-storage/src/main/java/com/google/cloud/storage/DefaultBufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/MinFlushBufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/OtelStorageDecorator.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnbufferedWritableByteChannelSession.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BidiUploadTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/DefaultBufferedWritableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITAppendableUploadTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/MinFlushBufferedWritableByteChannelTest.java

Allows blocking the invoking thread until the number of bytes acknowledged by GCS matches the number of written bytes prior to calling flush().

feat: add AppendableUploadWriteableByteChannel#flush()

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobInfoTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadMaskTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITOptionRegressionTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/ObjectArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/StorageArbitraries.java

b/434726122
Add support for object contexts

feat: add BlobInfo.ObjectContexts

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonUtils.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Utils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/JsonUtilsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITNestedUpdateMaskTest.java

Add JsonUtils class to provide some helpers for performing arbitrarily deep field selection. Our existing implementation is flat for everything exception metadata, with the addition of object contexts we now have an N depth diff (metadata is always depth 2, but a context path is `contexts.custom.<key>.value`) and the value of the key is an object instead of a string. We accomplish this arbitrary diffing by first flattening the src object to a map of paths to leaves and their corresponding string values. Then we diff the keys to produce a new map, and then treeify that new map back to a json structure.
This is quite robust, but isn't terribly efficient so we only use it for contexts and metadata fields.
Update BlobInfo.BuilderImpl#setContexts to deeply resolve the diff against the provided …

chore: update BlobInfo.contexts diff handling to be deep rather than shallow

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BidiAppendableUnbufferedWritableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BidiUploadState.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BidiAppendableUnbufferedWritableByteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BidiUploadTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BidiUploadTestUtils.java

When finalizing an appendable upload depending on how quickly gcs is acking bytes, we could run into a case where finish_write: true was sent before all bytes had been enqueued.
Regression introduced in 2.57.0

fix: fix appendable upload finalization race condition

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobAppendableUploadImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ITAppendableUploadTest.java

FileChannel.transferTo first checks if the destination is open. Our tests didn't catch this before because they did not probe openness before writing bytes.

fix: fix IllegalMonitorStateException thrown from BlobAppendableUpload.isOpen()

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadBlobWriteSessionConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadWritableByteChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ParallelCompositeUploadWritableByteChannelTest.java

If a PCU is initiated with a BlobInfo from the current generation of an object, the crc32c and md5 will be included in all compose requests. Update the code to properly clear when necessary, and to only apply a provided value to the final compose if crc32cMatch or md5Match were specified.

fix: update PCU request building logic to properly clear crc32c and md5
