versions.txt

This should fix the release process to allow the release-please bot to propose releases

build: add versions.txt manifest

---

google-cloud-storage/src/test/java/com/google/cloud/storage/CopyRequestTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/OptionTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageOptionsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/V4SigningTest.java

fix deprecations and other warnings

---

README.md

@kolea2 deliberately staying off 3.3.0 until #57 is fixed

chore(deps): Update BOM to 3.2.0

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java

fix: make the getStorageClass() method public

---

google-cloud-storage/pom.xml
pom.xml

chore(deps): update conformance test

---

google-cloud-storage/pom.xml
pom.xml

Update and stop duplicating managed versions

---

google-cloud-storage/pom.xml
pom.xml

update guava and GAX

---

pom.xml

Remove duplicate dependency

---

pom.xml

deps: update to gRPC 1.27.0

---

pom.xml

@chingor13 to avoid linkage errors

Revert to 1.27.2

---

samples/install-without-bom/pom.xml
samples/snapshot/pom.xml
samples/snippets/pom.xml

samples: fix install-without-bom version

---

google-cloud-storage/src/test/java/com/google/cloud/storage/V4SigningTest.java
pom.xml

Updates conformance test dependency

deps: update conformance test dep

---

synth.py

chore: fix synth.py error and enable multiple autosynth commits

---

pom.xml

deps: pin mockito version to work with java 7

---

google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpcSpans.java

chore: remove deprecated registration of the span names

---

README.md

docs: update readme to point client libarary documentation

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java

Add doc for equals method in blob

---

google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

chore:  Suppressing Warnings

---

.gitignore

chore: ignore backup files

---

google-cloud-storage/pom.xml
pom.xml

1. Remove unused dependency ignore configuration
1. Update google-cloud-shared-config v0.9.0
1. Update KMS test dependencies v0.86.0

dep: update dependencies

---

CONTRIBUTING.md
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

test: ITStorageTest requires Permission 'cloudkms.keyRings.setIamPolicy'

---

CONTRIBUTING.md
synth.py

fix: Ignore CONTRIBUTING.md

---

.kokoro/nightly/integration.cfg

fix: set IT_SERVICE_ACCOUNT_EMAIL for nightly integration test

---

google-cloud-storage/clirr-ignored-differences.xml

docs: update link

---

pom.xml

deps: update org.apache.httpcomponents

---

pom.xml

deps: update truth

---

.github/release-please.yml
.github/sync-repo-settings.yaml

build: configure branch sp-release as a release branch

---

.github/workflows/ci.yaml

feat: update ci config for 1.113.14-sp branch

---

.github/release-please.yml
.github/sync-repo-settings.yaml

Update the release please config in preparation for patching v1.106.0
Fixes #843 ☕️

build: Add OLM fix branch to release please config

---

.github/release-please.yml
.github/sync-repo-settings.yaml

build: configure branch 1.111.3-patch as a release branch

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java

Add @JesseLovelace's lifecycle patch fix to 1.111.3-patch branch

fix: patch life cycle validation fix (1.111.3 patch)

---

.kokoro/build.sh
.kokoro/coerce_logs.sh
.kokoro/common.sh
.kokoro/continuous/readme.cfg
.kokoro/dependencies.sh
.kokoro/nightly/integration.cfg
.kokoro/readme.sh
.kokoro/release/publish_javadoc.cfg
.kokoro/release/publish_javadoc11.cfg
.kokoro/release/publish_javadoc11.sh
.kokoro/release/snapshot.sh
.kokoro/release/stage.cfg
.kokoro/release/stage.sh

Release failed @ maven due to auth issues caused by outdated kokoro config. This brings in the latest kokoro config files.
https://github.com/googleapis/java-storage/issues/895

build: add latest kokoro configuration (1.111.3 branch)

---

google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpcSpans.java

rename create(String,Map) -> list(String,Map)
Fixes #942

fix: incorrectly labeled span list(String,Map)

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ResumableMedia.java
google-cloud-storage/src/test/java/com/google/cloud/storage/ResumableMediaTest.java

test: add positive case for ResumableMedia#startUploadForSignedUrl

---

.github/workflows/ci.yaml

(cherry picked from commit 62b9925ac007790d07bbe4d79b55d5c1eaa5f7b6)

chore(1.113.14-sp): backport install maven 3.8.1 at runtime

---

google-cloud-storage/src/main/java/com/google/cloud/storage/NewRetryAlgorithmManager.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java

fix: address errors raised rewites(mapping 58)

---

google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java

fix: validate non-idempotent case for 81,82,83,84,85,86

---

google-cloud-storage/src/main/java/com/google/cloud/storage/NewRetryAlgorithmManager.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java

test(retry): correct setIamPolicy conformance tests test cases 240 and 18

---

.github/cherry-pick-bot.yml

See https://github.com/googleapis/repo-automation-bots/tree/main/packages/cherry-pick-bot

chore: enable cherry-pick-bot

---

google-cloud-storage/src/main/java/com/google/cloud/storage/PolicyHelper.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/test/java/com/google/cloud/storage/PolicyHelperTest.java

Cherry Pick PR #1177 into 2.1.x

fix: cherry pick IAM condition validation PR #1177

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java

Cherry Pick PR #1160 into 2.1.x

fix: cherry pick PR#1160

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

test: re-enable testHmacKey test

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

Reverts googleapis/java-storage#1250

Revert "test: skip testHmacKey test (#1239)"

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketInfoTest.java

* fix: Remove all client side validation for OLM, allow nonspecific lifecycle actions

fix: cherry pick #1160

---

samples/install-without-bom/pom.xml
samples/native-image-sample/pom.xml
samples/pom.xml
samples/snapshot/pom.xml
samples/snippets/pom.xml
samples/snippets/src/test/java/com/example/storage/ITBucketSnippets.java
samples/snippets/src/test/java/com/example/storage/ITObjectSnippets.java
samples/snippets/src/test/java/com/example/storage/ITStorageSnippets.java
samples/snippets/src/test/java/com/example/storage/QuickstartSampleIT.java

* chore(build): add <relativePath/> in order to prevent relativePath warning
* build(samples): add httpclient and httpmime to samples/snippets/pom.xml
* samples/snippets was failing in test-compile phase due to missing dependency declarations
* core(samples): replace all System.setOut with StdOutCaptureRule

chore(samples): samples cleanup

---

google-cloud-storage/src/main/java/com/google/cloud/storage/StorageOptions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageOptionsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/spi/v1/AuditingHttpTransport.java
google-cloud-storage/src/test/java/com/google/cloud/storage/spi/v1/HttpRpcContextTest.java

fix: privatize invocation flag

---

google-cloud-storage/src/main/java/com/google/cloud/storage/StorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageOptionsTest.java

chore: privatize invocation id getters

---

samples/snippets/src/test/java/com/example/storage/bucket/CreateBucketPubSubNotificationTest.java
samples/snippets/src/test/java/com/example/storage/bucket/DeleteBucketPubSubNotificationTest.java
samples/snippets/src/test/java/com/example/storage/bucket/ListPubSubNotificationsTest.java
samples/snippets/src/test/java/com/example/storage/bucket/PrintPubSubNotificationTest.java

This should prevent parallel test runs from colliding with one another.

test: Adding unique identifier to Notification Samples Topics

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

Refactor `afterClass()` to attempt cleanup of each resource independently
Explicitly shutting down the grpc channel for KMS prevents the following exception from error being reported
```
*~*~*~ Channel ManagedChannelImpl{logId=1, target=cloudkms.googleapis.com:443} was not shutdown properly!!! ~*~*~*
Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
at …
```

chore(test): update ITStorageTest to explicitly shutdown the grpc channel for KMS

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Utils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketPropertyTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/JqwikTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/BucketArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/StorageArbitraries.java
google-cloud-storage/src/test/resources/META-INF/services/net.jqwik.api.providers.ArbitraryProvider

feat: bucket metadata

---

.kokoro/presubmit/graalvm-native-17.cfg
owlbot.py

build: include service account info in native image JDK 17 test script

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageFixture.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

* Add StorageFixture to manage the test scoped lifecycle of a storage instance
* Update ITStorageTest to use new fixture
* Update ITBlobReadChannelTest to use new fixture

feat: make Storage extend AutoClosable

---

google-cloud-storage/pom.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/ApiaryConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Utils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketPropertyTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/DateTimeCodecPropertyTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/BucketArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/StorageArbitraries.java

Introducing more support for BucketInfo conversions

feat: BucketInfo conversion for gRPC

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Utils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/BucketArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/StorageArbitraries.java

Add remaining fields for Bucket metadata (defaultObjectAcls, Owner, Logging, Cors, and IamConfiguration) 
Fix OLM deleteRules encode/decode to only function when Rules are exactly what's expected otherwise return null.

feat: Bucket metadata grpc

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GrpcTransformPageDecoratorTest.java

feat: TransformPageDecorator 

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java

feat: add gRPC create bucket

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java

Update GrpcStorageImpl methods to populate user project information when applicable

chore: wire through X-Goog-User-Project header for grpc calls

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java

feat: implement GrpcStorageImpl#compose(ComposeRequest): Blob

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BaseConvertablePropertyTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/JqwikTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/PackagePrivateMethodWorkarounds.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/BucketArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/HmacKeyMetadataArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/ObjectArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/ServiceAccountArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/StorageArbitraries.java

1. Update Arbitraries to inject null values for applicable fields
2. Fix misc mapping issues in Grpc Codecs exposed by new null values

WIP chore: Property test robustness improvements

---

README.md
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/TestBench.java

chore: upgrade testbench v0.28.0

chore: upgrade testbench v0.28.0

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BufferHandle.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ChannelSession.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java

Update location of double check lazy initialization idiom to follow the flow
outlined in Effective Java, 3rd Edition Item 83

chore: update double check lazy initialization idiom

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobWriteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITKmsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITSignedUrlTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java

Split and consolidate integration tests into their own `IT*.java` files:
1. SignedUrl
2. KMS
3. BlobWriteChannel
This is part 1. the eventual goal is that ITStorageTest is deleted in favor of groups of tests being in their own files.

test: refactor Integration tests Part 1

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BackwardCompatibilityUtils.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Retrying.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageException.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Utils.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BackwardCompatibilityUtilsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/StorageExceptionGrpcCompatibilityTest.java

Update StorageException#coalesce to account for subclasses of ApiException returned by the gapic client.

chore: preliminary implementation of gRPC status code to HTTP Status code translation

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java

Fix merge break introduced in #1576

chore: fix bad merge

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
samples/snippets/src/main/java/com/example/storage/bucket/CreateBucketDualRegion.java

samples: Adding Metadata to dual-region sample

---

README.md
pom.xml
samples/snippets/src/test/java/com/example/storage/ITHmacSnippets.java
samples/snippets/src/test/java/com/example/storage/ITObjectSnippets.java
samples/snippets/src/test/java/com/example/storage/bucket/DeleteBucketPubSubNotificationTest.java
samples/snippets/src/test/java/com/example/storage/bucket/ListPubSubNotificationsTest.java
samples/snippets/src/test/java/com/example/storage/object/RemoveFileOwnerTest.java

test: add retries to flaky sample tests

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITAccessTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobWriteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITDownloadBlobWithoutAuth.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITHmacTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITServiceAccountTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITWriteChannelConnectionPoolTest.java

test: ITStorage converted to ITObjectTest

---

README.md
google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
samples/snippets/src/main/java/com/example/storage/bucket/CreateBucketDualRegion.java

This reverts commit 7ac6206e11fc405f58039ba854dcb649ef03c101.
This commit will be added back in 2 additional PRs, one for the feature addition of a toString method to CustomPlacementConfig and then an update to the sample. 
Fixes #1587☕️

Revert "samples: Adding Metadata to dual-region sample (#1581)"

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java

feat: Add toString method for CustomPlacementConfig

---

google-cloud-storage/clirr-ignored-differences.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/CopyWriter.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GapicCopyWriter.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcRetryAlgorithmManager.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/HttpCopyWriter.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/test/java/com/google/cloud/storage/CopyWriterTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/UnifiedOptsGrpcTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITGrpcTest.java

Refactoring by pushing current CopyWriter implementation down to new
HttpCopyWriter and makeing CopyWriter abstract.

feat: implement GrpcStorageImpl#copy

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java

DeleteRule is deprecated, and poised for removal. BlobInfo.Builder will automatically convert any DeleteRule provided to it to the corresponding LifecycleRule with delete condition.
Our Conversions classes need only encode/decode LifecycleRule.

chore: remove DeleteRule handling in GrpcConversions

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/BucketArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/ObjectArbitraryProvider.java
google-cloud-storage/src/test/java/com/google/cloud/storage/jqwik/StorageArbitraries.java

* test: increase coverage for Bucket website
* test: increase coverage for Bucket ctime, utime
* chore: fixup edge case generation for RPO and etag based on learnings from jlink/jqwik#384
* chore: fixup edge case generation for Storage class and Rule.Condition
* chore: fixup bucket logging edge case handling
* chore: fixup edge case generation for Object first level fields
* chore: fixup generation for ObjectChecksums

test: increase coverage and edge case generation for GrpcConversions

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITDownloadToTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITHmacTest.java

test: Adding GRPC to ITDownloadTo and ITHmacTests

---

google-cloud-storage/pom.xml
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITCustomJsonFactoryTest.java

feat: add constructor parameter for JsonFactory to HttpStorageRpc

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketFixture.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITGrpcTest.java

Add helper method to BucketFixture to generate a new bucket name following the configured pattern.

feat: implement GrpcStorageImpl#lockRetentionPolicy

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketTest.java

test: ITBucket test and minor bug fixes

---

google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/test/java/com/google/cloud/storage/UpdateMaskTest.java

Add new tests to validate expected modified fields match
Related b/247133805

chore: update handling of BlobInfo and BucketInfo to track which fields are modified

---

google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/test/java/com/google/cloud/storage/DetectContentTypeTest.java

Motivated by https://github.com/googleapis/java-storage/pull/1642/files#r977083249

test: add tests for UnifiedOpts.DetectContentType to verify for some common extensions

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITAccessTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITNotificationTest.java

test: Stub tests for GRPC integration

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITKmsTest.java

test: Enable GRPC for ITKmsTest

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java
samples/snippets/src/test/java/com/example/storage/bucket/CreateBucketDualRegionTest.java

chore: patch Dual Region Tests to work with service changes

---

README.md
samples/snippets/src/main/java/com/example/storage/bucket/CreateBucketDualRegion.java

This cannot be merged until https://github.com/googleapis/java-storage/commit/51aca10fafe685ed9e7cb41bc4ae79be10feb080 is released.

samples: Add Metadata to dual-region sample

---

samples/snippets/src/main/java/com/example/storage/object/ReleaseEventBasedHold.java
samples/snippets/src/main/java/com/example/storage/object/ReleaseTemporaryHold.java
samples/snippets/src/main/java/com/example/storage/object/SetEventBasedHold.java
samples/snippets/src/main/java/com/example/storage/object/SetObjectMetadata.java
samples/snippets/src/main/java/com/example/storage/object/SetTemporaryHold.java
samples/snippets/src/main/java/com/example/storage/object/UploadObject.java

samples: adding preconditions to some of the samples

---

.kokoro/presubmit/graalvm-native-17.cfg
.kokoro/presubmit/graalvm-native.cfg

chore: update native image checks to graalvm-22.3.0

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadMaskTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketReadMaskTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITOptionRegressionTest.java

* ITOptionRegressionTest#bucket_BucketSourceOption_userProject_String
* ITBlobReadMastTest[ACL]
* ITBlobReadMastTest[ETAG]
* ITBucketReadMastTest[ACL]
* ITBucketReadMastTest[ETAG]

test: cleanup/re-enable some ignored tests

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/TestBench.java

A proposed change to testbench does not as gracefully shutdown when `process.destroy()` is called. Update our stop method to fall back to using `docker kill` if `process.destroy()` appears to not be effective.

test: update TestBench#stop to explicitly kill the container if the process doesn't stop gracefully

---

google-cloud-storage/src/test/java/com/google/cloud/storage/GapicUnbufferedWritableByteChannelTest.java

In very rare cases GapicUnbufferedWritableByteChannelTest#resumableUpload will fail with a permission denied error while running in CI. Thus far I've not be able to reproduce the failure locally even after running the tests thousands of times. This PR adds a log message with the expected vs resolved state in the case of failure in the hope we will be able to get more information the next time it does fail in CI.
Related to https://github.com/googleapis/java-storage/issues/1748

chore(test): increase debug logging for failure cases in GapicUnbufferedWritableByteChannelTest

---

.github/release-please.yml
.github/sync-repo-settings.yaml
samples/snippets/src/main/java/com/example/storage/object/UploadObject.java

feat: setting up 2.15.x

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadResult.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadResult.java

chore: Add null check based of TransferStatus to Download/Upload Result

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadJob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManager.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadJob.java

chore: move TransferManagerConfig to own file and add Parallel{Upload,Download}Config to jobs

---

google-cloud-storage/src/main/java/com/google/cloud/storage/PackagePrivateMethodWorkarounds.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadCallable.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ParallelUploadConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerUtils.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadCallable.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadJob.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITTransferManagerTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/transfermanager/TransferManagerTest.java

feat: First Pass Implementation of UploadMany

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITAccessTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketLifecycleRulesTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketLifecycleTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBucketTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITKmsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITNestedUpdateMaskTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java

Reverts googleapis/java-storage#1917

Revert "chore: ignore Update related gRPC tests which are failing due to b/270215524"

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadCallable.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ParallelDownloadConfig.java

feat: Change Prefix to Download Directory

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcBlobWriteChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/PackagePrivateMethodWorkarounds.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobWriteChannelTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITWriteChannelTest.java

Add new integration tests for both json and grpc to verify openness

fix: make GrpcBlobWriteChannel open upon construction

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferStatus.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadCallable.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITTransferManagerTest.java

feat: Error Handling and Transfer Status assignment FAILED_TO_START

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITTransferManagerTest.java

Some tests for All successes but one failure for Upload/Download blobs. I also moved some of the upload tests up in the file so they were grouped together. Just a mechanical change.

test: Success and failure combined tests

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadJob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadResult.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ParallelDownloadConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ParallelUploadConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManager.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferStatus.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadJob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadResult.java

chore: Add BetaApi Annotation to public classes and methods

---

.github/release-please.yml
.github/sync-repo-settings.yaml

chore: create 2.22.x branch

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ChunkedDownloadCallable.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DirectDownloadCallable.java

feat: Add validation around bytes received vs bytes expected

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadJob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/DownloadResult.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerConfig.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferStatus.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadJob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/UploadResult.java

Javadocs for Upload/Download job, Upload/Download Result, TransferManagerConfig and TransferStatus

docs: Javadocs for remainder of Transfer Manager

---

google-cloud-storage/src/test/java/com/google/cloud/storage/ITSyncAndUploadUnbufferedWritableByteChannelPropertyTest.java

New property tests induce failures at random points and run a number of permutations

test: add property based test ITSyncAndUploadUnbufferedWritableByteChannelPropertyTest

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/test/java/com/google/cloud/storage/SerializationTest.java
google-cloud-storage/src/test/resources/com/google/cloud/storage/composeRequest.ser.properties

Update ComposeRequest to leverage Opts internally instead of BlobTargetOptions

chore: refactor ComposeRequest to use Opts

---

pom.xml

Created a profile for packaging the CLI without including it in our releases.

chore(benchmarking): Add a profile to build the SSB cli

---

google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadException.java
google-cloud-storage/src/main/java/com/google/cloud/storage/ParallelCompositeUploadWritableByteChannel.java

Tweak public api to be List vs ImmutableList so we are not hard coded against guava.

chore: make ParallelCompositeUploadException public

---

README.md
storage-shared-benchmarking/src/main/java/com/google/cloud/storage/benchmarking/StorageSharedBenchmarkingCli.java

chore(benchmarking): Add in W1R3 with GRPC DirectPath

---

.kokoro/presubmit/graalvm-native-17.cfg
.kokoro/presubmit/graalvm-native.cfg

chore: update ghcr.io/graalvm/graalvm-ce docker tag to v22.3.3

---

README.md
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/XGoogApiClientHeaderProvider.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/XGoogApiClientHeaderProviderTest.java

chore: Add in TM entry for x-goog-api-client

---

.github/release-please.yml
.github/sync-repo-settings.yaml

feat: next release from main branch is 2.31.0

---

google-cloud-storage-control/pom.xml
google-cloud-storage-control/src/test/java/com/google/storage/control/v2/ITFoldersTest.java

Added a short IT for HNS Folder creation to test out new storage control client.

test: add IT for HNS bucket

---

google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java

Cherry pick from https://github.com/googleapis/java-storage/pull/2342 to fix the bug in the latest LTS version

fix: Add an exception to zero byte uploads on CreateFrom

---

google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java

Bug fix onto the current LTS branch

fix: Add an exception to zero byte uploads on CreateFrom (#2342)

---

README.md
storage-shared-benchmarking/src/main/java/com/google/cloud/storage/benchmarking/StorageSharedBenchmarkingCli.java

chore(benchmarking): Use api when determining workload runs

---

storage-shared-benchmarking/src/main/java/com/google/cloud/storage/benchmarking/StorageSharedBenchmarkingCli.java

chore(benchmarking): fix typo, bidi changed to bidi_enabled

---

google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/TransferManagerImpl.java

fix: ParallelCompositeUpload in Transfer Manager hangs when encountering OOM

---

README.md
google-cloud-storage/src/test/java/com/google/cloud/storage/BlobTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/BucketTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/CopyWriterTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/testing/RemoteStorageHelperTest.java

Re-adds most of the coverage that was lost when all the EasyMock tests were deleted, but as Mockito tests

test: add mockito tests

---

samples/snippets/src/main/java/com/example/storage/managedfolders/CreateManagedFolder.java
samples/snippets/src/main/java/com/example/storage/managedfolders/DeleteManagedFolder.java
samples/snippets/src/main/java/com/example/storage/managedfolders/GetManagedFolder.java
samples/snippets/src/main/java/com/example/storage/managedfolders/ListManagedFolders.java
samples/snippets/src/test/java/com/example/storage/managedfolders/CreateManagedFolderTest.java
samples/snippets/src/test/java/com/example/storage/managedfolders/DeleteManagedFolderTest.java
samples/snippets/src/test/java/com/example/storage/managedfolders/GetManagedFolderTest.java
samples/snippets/src/test/java/com/example/storage/managedfolders/ListManagedFolderTest.java

docs: Managed Folders samples

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/BackendResources.java

Universes as well as adhoc dev are likely on the horizon, this PR makes it easier to add new backends in the integration test runner.
By using a switch instead of a ternary new switch branches can be added in a diff and easily re-applied.
By passing the list of RegistryEntries directly to the constructor makes it easier for a diff to insert new elements.

chore(test): slightly restructure BackendResources to make more friendly to adding new values to Backends

---

README.md
samples/snippets/src/test/java/com/example/storage/QuickstartSampleIT.java

test: Ignore failing DirectPath tests

---

.github/workflows/hermetic_library_generation.yaml

chore: skip hermetic generation on fork PRs

---

.github/trusted-contribution.yml

chore: Add release-please to trusted contributors

---

google-cloud-storage/src/main/java/com/google/cloud/storage/OpenTelemetryBootstrappingUtils.java

Enabling `grpc.lb.locality` label
https://github.com/grpc/proposal/blob/master/A78-grpc-metrics-wrr-pf-xds.md#weighted-round-robin-lb-policy

feat: enable grpc.lb.locality label for client-side metrics

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java

chore: attempt to drain the stream iterator

---

.kokoro/build.sh
.kokoro/presubmit/integration.cfg
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/HttpStorageOptions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITUniverseDomainTest.java

Adds integration tests for Universe Domain configuration, accessing secret manager to get the environment variables.
Also changes the usage of the ServiceOptions.getResolvedApiaryHost helper to accommodate the changes made in https://github.com/googleapis/sdk-platform-java/commit/5f17e62a7b0f10035205ec4197b8f77388b059f8

feat: adds integration tests for Universe Domain configuration

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/RpcMethodMappings.java
google-cloud-storage/src/test/java/com/google/cloud/storage/conformance/retry/TestRetryConformance.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITGrpcTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITHmacTest.java

Partial revert of 84e4adf19a747471dab224bf8efaf2a21b8b2b37

fix: remove server unimplemented GrpcStorageImpl#{get,list,create,delete,Update}HmacKey

---

.github/release-please.yml
.github/sync-repo-settings.yaml

chore: release 2.38.x

---

renovate.json

In this PR:
- Group dependency updates from sdk-platform-java in one PR.

chore: group sdk-platform-java dep updates

---

google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java

Fixes #2770
Not originally detected due to https://github.com/googleapis/storage-testbench/issues/685

fix: fix createFrom resumable upload retry offset calculation

---

google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java
google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java
google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/JsonConversions.java
google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadMaskTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITOptionRegressionTest.java

Reverts googleapis/java-storage#2768

Revert "feat: adds support for restore token"

---

google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITKmsTest.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/BackendResources.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/KmsFixture.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/MetadataService.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/Registry.java
google-cloud-storage/src/test/java/com/google/cloud/storage/it/runner/registry/Zone.java

Update KmsFixture and BucketFixtures to use the same region for location of keys and buckets.

test: add new Zone fixture to IT test runner registry

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java

By categorizing as retriable the client will be allowed to retry the request rather than failing out.
[1] [`WatchdogTimeoutException`](https://github.com/googleapis/sdk-platform-java/blob/v2.53.0/gax-java/gax/src/main/java/com/google/api/gax/rpc/WatchdogTimeoutException.java#L45)

fix: categorize a WatchdogTimeoutException as retriable for grpc ReadObject

---

.github/release-please.yml
.github/sync-repo-settings.yaml

feat: next release from main branch is 2.50.0

---

google-cloud-storage/src/main/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannel.java
google-cloud-storage/src/test/java/com/google/cloud/storage/GapicUnbufferedReadableByteChannelTest.java

Add test to ensure things are cleaned up

fix: fix grpc ReadObject memory leak introduced in 2.51.0

---

renovate.json

https://github.com/googleapis/sdk-platform-java/pull/3800

chore: hermetic build to manage the graalvm presubmit image versions

---

.github/scripts/update_generation_config.sh

Unfortunately, https://github.com/googleapis/sdk-platform-java/pull/3853 cannot be automatically propagated. 
This PR manually updates this script with the latest.

chore: manual update of update_generation_config.sh

---

google-cloud-storage/src/main/java/com/google/cloud/storage/OtelStorageDecorator.java

Accidentally opened after some debugging in #3255

chore: make OtelStorageDecorator package private again
